/**
 * BEEKEEPING — Members Area Data (PT)
 */

const APP_DATA = {
    config: {
        brandName: "Apicultura para Iniciantes",
        contactEmail: "trinityag01@gmail.com",
        emailSubject: "Questão sobre o acesso ao curso (Apicultura)",
        emailBodyTemplate: "Olá equipa de suporte! Preciso de ajuda com a minha área de membros de Apicultura.%0A%0AO meu nome é: ______.",
        showFloatingHelp: true
    },

        videos: [
        { id: 'v1', title: "Curso de meliponicultura - Parte 1 - Quem são as abelhas sem ferrão?", duration: 'Meliponicultura - Vídeo 1', youtubeId: '_YkMgucy6Dg' },
        { id: 'v2', title: "Curso de Meliponicultura - Parte 2 - Biologia geral das abelhas sem ferrão", duration: 'Meliponicultura - Vídeo 2', youtubeId: 'tXT4THzgE8Q' },
        { id: 'v3', title: "Curso de Meliponicultura - Parte 3 - Por que criar abelhas sem ferrão?", duration: 'Meliponicultura - Vídeo 3', youtubeId: 'gWfMj0pHLcY' },
        { id: 'v4', title: "Curso de Meliponicultura - Parte 4 - Técnicas de manejo de abelhas sem ferrão", duration: 'Meliponicultura - Vídeo 4', youtubeId: 'dZ_8bZJpEIc' },
        { id: 'v5', title: "Ninho armadilha", duration: 'Meliponicultura - Vídeo 5', youtubeId: 'mBOqazgb-qs' },
        { id: 'v6', title: "Transferência", duration: 'Meliponicultura - Vídeo 6', youtubeId: 'cd8q31Fl8cc' },
        { id: 'v7', title: "Colheita de mel", duration: 'Meliponicultura - Vídeo 7', youtubeId: 'mJ1_RY10AQE' },
        { id: 'v8', title: "Divisão de mandaguari", duration: 'Meliponicultura - Vídeo 8', youtubeId: 'Qw-RktzdXt4' },
        { id: 'v9', title: "Transfer of jataí bees to INPA model box", duration: 'Meliponicultura - Vídeo 9', youtubeId: 'upegEyTkUEw' },
        { id: 'v10', title: "colhendo mel de jatai em casa", duration: 'Meliponicultura - Vídeo 10', youtubeId: 'XWKlDytpgHY' },
        { id: 'v11', title: "6 Essential Tips for Making Your Own Mead - How to Make Mead", duration: 'Hidromel - Vídeo 1', youtubeId: 'Z_ITF16bD6s' },
        { id: 'v12', title: "OXIGENAÇÃO do MOSTO do HIDROMEL - Quando fazer a oxigenação", duration: 'Hidromel - Vídeo 2', youtubeId: 'Wz01bfFu_yI' },
        { id: 'v13', title: "6 COISAS que VOCÊ NÃO SABE ou NUNCA TE CONTARAM sobre o HIDROMEL - VÍDEO DO MÊS", duration: 'Hidromel - Vídeo 3', youtubeId: 'jG5gRlSet0Q' },
        { id: 'v14', title: "MINHA PRIMEIRA RECEITA DE HIDROMEL -  MOMENTO DO HIDROMEL 031", duration: 'Hidromel - Vídeo 4', youtubeId: 'JoG38VOeG8Q' },
        { id: 'v15', title: "POSSO USAR GELATINA PARA CLARIFICAR MEU HIDROMEL? - MOMENTO DO HIDROMEL 004", duration: 'Hidromel - Vídeo 5', youtubeId: 'O3QaGId5k3A' },
        { id: 'v16', title: "QUANDO FAZER A PRIMEIRA TRASFEGA  - MOMENTO DO HIDROMEL 039", duration: 'Hidromel - Vídeo 6', youtubeId: 'ubw3H6WLfXc' },
        { id: 'v17', title: "TEMPERATURA DE FERMENTAÇÃO DO HIDROMEL - MOMENTO DO HIDROMEL 012", duration: 'Hidromel - Vídeo 7', youtubeId: '3tQ7tsGpxLQ' },
        { id: 'v18', title: "MEAD MATURATION – The correct temperature – MEADING TIME 025", duration: 'Hidromel - Vídeo 8', youtubeId: 'fd1NZPMDRoY' },
        { id: 'v19', title: "LOCAL PARA PRODUZIR HIDROMEL - Em que local posso produzir em casa?  -  MOMENTO DO HIDROMEL 028", duration: 'Hidromel - Vídeo 9', youtubeId: '9Dsnqczk1fk' },
        { id: 'v20', title: "COMO ESTÃO AS PRODUÇÕES CASEIRAS NO BRASIL - MOMENTO DO HIDROMEL 037", duration: 'Hidromel - Vídeo 10', youtubeId: '1qY6XcBlph4' },
        { id: 'v21', title: "O MEL no HIDROMEL - MOMENTO DO HIDROMEL 032", duration: 'Hidromel - Vídeo 11', youtubeId: '-jzOr79tLo4' },
        { id: 'v22', title: "How to Make Semi-Dry or Sweet Mead [Techniques I Use] - Mead Moment 045", duration: 'Hidromel - Vídeo 12', youtubeId: 'Vt49ubMRtL0' },
        { id: 'v23', title: "Quanto TEMPO AMADURECER [Hidromel] - MOMENTO DO HIDROMEL 055", duration: 'Hidromel - Vídeo 13', youtubeId: 'szbPLdGYd5g' },
        { id: 'v24', title: "MAPA DE CERVEJA PODE SER USADO PARA HIDROMEL? -  MOMENTO DO HIDROMEL 054", duration: 'Hidromel - Vídeo 14', youtubeId: 'v0zwduA0vSs' },
        { id: 'v25', title: "HIDROMEL DÁ DINHEIRO? [Viver de Hidromel no Brasil] - MOMENTO DO HIDROMEL 050", duration: 'Hidromel - Vídeo 15', youtubeId: 'EVbQw5RBsEE' },
        { id: 'v26', title: "NO BUBBLES in the AIRLOCK | Tips on how to check fermentation | MEAD MOMENT 073", duration: 'Hidromel - Vídeo 16', youtubeId: 'V4CuJf8krnI' },
        { id: 'v27', title: "Qual é a GARRAFA DO HIDROMEL? [tipo e tamanho] -  MOMENTO DO HIDROMEL 056", duration: 'Hidromel - Vídeo 17', youtubeId: 'xjxBQrtdKaU' },
        { id: 'v28', title: "QUANDO ENGARRAFAR MEU HIDROMEL - MOMENTO DO HIDROMEL 062", duration: 'Hidromel - Vídeo 18', youtubeId: 'KwgBs7HOY2s' },
        { id: 'v29', title: "O USO DA GELADEIRA NA FERMENTAÇÃO - MOMENTO DO HIDROMEL 061", duration: 'Hidromel - Vídeo 19', youtubeId: '0ODgRMRYlmY' },
        { id: 'v30', title: "MOSTO A QUENTE OU FRIO [corte da LIVE  TÉCNICAS DE PRODUÇÃO DE HIDROMEL]", duration: 'Hidromel - Vídeo 20', youtubeId: 'FcfFx2bHyD8' },
        { id: 'v31', title: "AS TONALIDADES DO HIDROMEL - MOMENTO DO HIDROMEL 060", duration: 'Hidromel - Vídeo 21', youtubeId: 'hs_ItQwl7F4' },
        { id: 'v32', title: "Cork or cap on the bottle [which is the best option] - Mead Moment 065", duration: 'Hidromel - Vídeo 22', youtubeId: 'T6BOohRnpzo' },
        { id: 'v33', title: "DÁ PARA FAZER MICRO LOTES DE HIDROMEL? [como medir uma mini batch]  -  MOMENTO DO HIDROMEL 064", duration: 'Hidromel - Vídeo 23', youtubeId: 'd8aKEw-IndY' },
        { id: 'v34', title: "HEADSPACE no HIDROMEL | O quê é e quanto deixar no fermentador | MOMENTO DO HIDROMEL 094", duration: 'Hidromel - Vídeo 24', youtubeId: 'A_RbGhB_J1E' },
        { id: 'v35', title: "ARROLHANDO o HIDROMEL | É fácil e rápido | MOMENTO DO HIDROMEL 071", duration: 'Hidromel - Vídeo 25', youtubeId: 'Sj0Kkl14ZdU' },
        { id: 'v36', title: "EQUIPAMENTOS PARA FAZER O HIDROMEL | Lista Completa e Serve para outras Bebidas | VÍDEOS DO MÊS", duration: 'Hidromel - Vídeo 26', youtubeId: 'ZwnMGENwnm0' },
        { id: 'v37', title: "O TEMPO para FAZER o HIDROMEL | Demora? |  MOMENTO DO HIDROMEL 075", duration: 'Hidromel - Vídeo 27', youtubeId: 'hNdQSIOYqUw' },
        { id: 'v38', title: "MAÇÃ NO HIDROMEL | Como usar | MOMENTO DO HIDROMEL 091", duration: 'Hidromel - Vídeo 28', youtubeId: 'VlGtOeYSQMk' },
        { id: 'v39', title: "DEPOIS do ADITIVO, quando POSSO ENGARRAFAR? - MOMENTO DO HIDROMEL 090", duration: 'Hidromel - Vídeo 29', youtubeId: 'vc_46LH4G7c' },
        { id: 'v40', title: "Existem RECEITAS PRONTAS de HIDROMEL? | alerta e desabafo | MOMENTO DO HIDROMEL 087", duration: 'Hidromel - Vídeo 30', youtubeId: '4f0-bBfJnDU' },
        { id: 'v41', title: "MISTURAR MÉIS para o HIDROMEL | Blend de meles na produção | MOMENTO DO HIDROMEL 092", duration: 'Hidromel - Vídeo 31', youtubeId: 'x4usXyL358w' },
        { id: 'v42', title: "COMO PLANEJAR UM HIDROMEL PARA GUARDA | ou não | MOMENTO DO HIDROMEL 095", duration: 'Hidromel - Vídeo 32', youtubeId: 'NC59easT3mk' },
        { id: 'v43', title: "DULÇOR do HIDROMEL no BRASIL | O quê diz a Legislação | MOMENTO DO HIDROMEL 099", duration: 'Hidromel - Vídeo 33', youtubeId: 'pElezopZ9BQ' },
        { id: 'v44', title: "DICAS para o  HIDROMEL SUAVE | doce | MOMENTO DO HIDROMEL 100", duration: 'Hidromel - Vídeo 34', youtubeId: 'cLSSr9vJEBY' },
        { id: 'v45', title: "MELOMEL, Quando Tirar as FRUTAS? |  MOMENTO DO HIDROMEL 104", duration: 'Hidromel - Vídeo 35', youtubeId: '1BxsXOM3JC0' },
        { id: 'v46', title: "How to REDUCE ALCOHOL in MUST - MEADING MOMENT 105", duration: 'Hidromel - Vídeo 36', youtubeId: 'DRe0tRXzIgI' },
        { id: 'v47', title: "SOUR MEAD - MOMENTO DO HIDROMEL 106", duration: 'Hidromel - Vídeo 37', youtubeId: 'ZpGfRjEspls' },
        { id: 'v48', title: "Hidromel NÃO TERMINADO | Pode dar problemas ? | MOMENTO DO HIDROMEL 107", duration: 'Hidromel - Vídeo 38', youtubeId: 'QfbCa9mXUmg' },
        { id: 'v49', title: "USANDO BARRIL PEQUENO | carvalho de madeira | MOMENTO DO HIDROMEL 108", duration: 'Hidromel - Vídeo 39', youtubeId: 'JIn8wAx8BuM' },
        { id: 'v50', title: "USAR LEVEDURA DE CERVEJA | como nutriente no HIDROMEL | MOMENTO DO HIDROMEL 109", duration: 'Hidromel - Vídeo 40', youtubeId: 'W6qP70eMVqk' },
        { id: 'v51', title: "PECTINASE para CLARIFICAR | funciona? | MOMENTO DO HIDROMEL 110", duration: 'Hidromel - Vídeo 41', youtubeId: '5kpKQJmxBpA' },
        { id: 'v52', title: "JABOTICABAS NO HIDROMEL | O chapéu do mosto | MOMENTO DO HIDROMEL 113", duration: 'Hidromel - Vídeo 42', youtubeId: '3clIHIxgYzo' },
        { id: 'v53', title: "BARRIL PEQUENO | outras considerações | MOMENTO DO HIDROMEL 115", duration: 'Hidromel - Vídeo 43', youtubeId: 'gb-dgQdVhro' },
        { id: 'v54', title: "CHIPS DE CARVALHO NO HIDROMEL | sanitização | MOMENTO DO HIDROMEL 118", duration: 'Hidromel - Vídeo 44', youtubeId: '-BgfiweX4ag' },
        { id: 'v55', title: "SAIS NA ÁGUA DO HIDROMEL | o mel também influencia? | MOMENTO DO HIDROMEL 121", duration: 'Hidromel - Vídeo 45', youtubeId: 'gR6m93y5Ihk' },
        { id: 'v56', title: "HIDROMEL MENOS ALCOOLICO  | dá para fazer?| MOMENTO DO HIDROMEL 122", duration: 'Hidromel - Vídeo 46', youtubeId: 'Dn4_RXGh3aw' },
        { id: 'v57', title: "STORING DILUTED BENTONITE (clarifier) ​​| Is it worth it? | MEAD MOMENT 124", duration: 'Hidromel - Vídeo 47', youtubeId: 'I7RJrznW-uM' },
        { id: 'v58', title: "COMO FAZER O BLEND NO HIDROMEL | Misturar dois Hidromeis | MOMENTO DO HIDROMEL 127", duration: 'Hidromel - Vídeo 48', youtubeId: 'lOrEkL0164k' },
        { id: 'v59', title: "ONDE ACHAR GARRAFAS | produção caseira de Hidromel | MOMENTO DO HIDROMEL 128", duration: 'Hidromel - Vídeo 49', youtubeId: 'G5GJR8jcnpk' },
        { id: 'v60', title: "MANIPULANDO BARRIS NO HIDROMEL | mais dicas para barris de madeira | MOMENTO DO HIDROMEL 130", duration: 'Hidromel - Vídeo 50', youtubeId: 'EeGZnrskXe0' },
        { id: 'v61', title: "ALTERNATIVAS PARA ARROLHAR O HIDROMEL | com menos $$ | MOMENTO DO HIDROMEL 132", duration: 'Hidromel - Vídeo 51', youtubeId: 'P2xTkME8bGU' },
        { id: 'v62', title: "MEL, UVAS PASSAS E ÁGUA,  vira hidromel ?  | MOMENTO DO HIDROMEL 134", duration: 'Hidromel - Vídeo 52', youtubeId: 'MtxlF4klTTY' },
        { id: 'v63', title: "AVINAGROU o HIDROMEL, e AGORA ? | Oxidou, Perdi Tudo? | MOMENTO DO HIDROMEL 135", duration: 'Hidromel - Vídeo 53', youtubeId: '2CgW_Daryrw' },
        { id: 'v64', title: "AIRLOCK | Tem problema entrar ar no fermentador? | MOMENTO DO HIDROMEL 137", duration: 'Hidromel - Vídeo 54', youtubeId: '79moAFUPuHs' },
        { id: 'v65', title: "ENGARRAFAR E CLARIFICAR | É para deixar a tampa meio aberta?|  MOMENTO DO HIDROMEL 138", duration: 'Hidromel - Vídeo 55', youtubeId: '2UsH7WWx_qA' },
        { id: 'v66', title: "TORNEIRA PARA FERMENTADOR | Dica de instalação | MOMENTO DO HIDROMEL 140", duration: 'Hidromel - Vídeo 56', youtubeId: 'XI4I90pN01Y' },
        { id: 'v67', title: "DILUIÇÃO DO HIDROMEL | Pode fazer? É fácil? Para que serve? | MOMENTO DO HIDROMEL 141", duration: 'Hidromel - Vídeo 57', youtubeId: 'z86eMtOGA4w' },
        { id: 'v68', title: "NÃO VOLTA A FERMENTAR MESMO? | É certeza? Existe uma forma certa? | MOMENTO DO HIDROMEL 142", duration: 'Hidromel - Vídeo 58', youtubeId: 'NKbYMD3CA68' },
        { id: 'v69', title: "HIDROMEL DE MEL FERMENTADO | Dá para fazer com esse mel? | MOMENTO DO HIDROMEL 143", duration: 'Hidromel - Vídeo 59', youtubeId: 'itKUUUWMzYM' },
        { id: 'v70', title: "FRUTA DENTRO DA GARRAFA | Dá para fazer como na cachaça? | MOMENTO DO HIDROMEL 145", duration: 'Hidromel - Vídeo 60', youtubeId: '6ybJdjV6ICA' },
        { id: 'v71', title: "ÁLCOOL SUPERIOR E SECAR O HIDROMEL | O que é isso? | MOMENTO DO HIDROMEL 146", duration: 'Hidromel - Vídeo 61', youtubeId: 'GxjiBBrxC90' },
        { id: 'v72', title: "CASCA DE LARANJA E DICA DE DEGUSTAÇÃO | Como escolher um Hidromel  | MOMENTO DO HIDROMEL 148", duration: 'Hidromel - Vídeo 62', youtubeId: 'X4VYEgIT3Ac' },
        { id: 'v73', title: "OXIGENAR COM CO² | Dica de livro para produção | MOMENTO DO HIDROMEL 149", duration: 'Hidromel - Vídeo 63', youtubeId: 'WnXSCK_Z5Kk' },
        { id: 'v74', title: "COLD CRASH, pode beber depois? | Indicação de documentário | MOMENTO DO HIDROMEL 150", duration: 'Hidromel - Vídeo 64', youtubeId: 'WxzoR9eYikA' },
        { id: 'v75', title: "FERMENTAR HIDROMEL EM 10 DIAS | Tem algum problema? + Detalhes | MOMENTO DO HIDROMEL 152", duration: 'Hidromel - Vídeo 65', youtubeId: 'vvIi3UB2N4c' },
        { id: 'v76', title: "MAIORES PRODUTORES DE HIDROMEL | países e tradição | PELO MUNDO MOMENTO DO HIDROMEL 160", duration: 'Hidromel - Vídeo 66', youtubeId: 'U9aQ1Sb0JNU' },
        { id: 'v77', title: "LEVEDURAS: QUANTIDADE IDEAL | Células viáveis, fatores relevantes | MOMENTO DO HIDROMEL 163", duration: 'Hidromel - Vídeo 67', youtubeId: 'sxZ0vXecSMg' },
        { id: 'v78', title: "De LEVEDURA VIVA a FERMENTO SECO | O Papel da Liofilização | MOMENTO DO HIDROMEL 165", duration: 'Hidromel - Vídeo 68', youtubeId: 'IIVzejYDZec' },
        { id: 'v79', title: "COMO Armazenar LEVEDURAS Corretamente? Evite Erros! | MOMENTO DO HIDROMEL 166", duration: 'Hidromel - Vídeo 69', youtubeId: '8MwbGroJyyI' },
        { id: 'v80', title: "🐝 GYPSY MEAD: Do you need to change your CNAE? | MEAD MOMENT 172", duration: 'Hidromel - Vídeo 70', youtubeId: 'GzhAnkPe37U' },
        { id: 'v81', title: "GYPSY MEAD AND MAP | More Tips to Get Started | MEAD MOMENT 177", duration: 'Hidromel - Vídeo 71', youtubeId: 'aw9cR5c82B8' },
        { id: 'v82', title: "✅ MEAD Clarification: Pros and Cons of COLLOIDAL SILICA | MEAD MOMENT 178", duration: 'Hidromel - Vídeo 72', youtubeId: 'xZUGRWyGwqA' },
        { id: 'v83', title: "MEAD refreshing like BEER? | MEAD MOMENT 179", duration: 'Hidromel - Vídeo 73', youtubeId: '08RxEgKTlCA' },
        { id: 'v84', title: "MEAD: How is FERMENTATION and MATURATION going? | MEAD MOMENT 181", duration: 'Hidromel - Vídeo 74', youtubeId: 'fUwE57rMiVM' },
        { id: 'v85', title: "Did MasterChef make a huge mistake with the Mead? 🍷 | Pairing #howtomakemead #shorts #meadcourse", duration: 'Hidromel - Vídeo 75', youtubeId: 'laE-C07IOSI' },
        { id: 'v86', title: "CAN I USE A DENSIMETRY FOR ALL DRINKS? MEAD MOMENT 188", duration: 'Hidromel - Vídeo 76', youtubeId: 'RDhLoXo82TM' },
        { id: 'v87', title: "WHAT DO THE BARREL | AND THE WOODS | HELP IN MEAD? - MEAD MOMENT 189", duration: 'Hidromel - Vídeo 77', youtubeId: 'GJJZOKqmC7c' },
        { id: 'v88', title: "🎥✨How YouTube and Mead changed my life (and can change yours too)", duration: 'Hidromel - Vídeo 78', youtubeId: 'k3P0fonJkMY' },
        { id: 'v89', title: "Can you make mead at home? #mead #howtomakemead", duration: 'Hidromel - Vídeo 79', youtubeId: 'g_iXC85OKK4' },
        { id: 'v90', title: "✨Premium Mead Yeast | Want quality? Do it with quality | Mead Moment 193", duration: 'Hidromel - Vídeo 80', youtubeId: '_vS1Kr5AReo' },
        { id: 'v91', title: "AJUSTE E SAIS NO HIDROMEL | MOMENTO DO HIDROMEL 195", duration: 'Hidromel - Vídeo 81', youtubeId: 'IXDMArGrvmo' },
        { id: 'v92', title: "I tested Brazilian yeast for mead | review 2026 | Mead yeast", duration: 'Hidromel - Vídeo 82', youtubeId: '3DE2zX2TD8M' },
        { id: 'v93', title: "Bucket filter in mead? + Important news about the segment! | Mead Moment 198", duration: 'Hidromel - Vídeo 83', youtubeId: 'Z1cGtctsKoc' },
        { id: 'v94', title: "APICULTURA MODERNA   🐝🧡🎥 Apicultura para Principiantes (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 1', youtubeId: 'hYxVqlndWVc' },
        { id: 'v95', title: "Tipos de ABEJAS  🐝🧡🎥 Apicultura para principiantes (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 2', youtubeId: 'MJdD5QOQ2pY' },
        { id: 'v96', title: "Tipos de COLMENAS 🐝🧡🎥 Que COLMENA es MEJOR (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 3', youtubeId: 'RCuuM8PQHKQ' },
        { id: 'v97', title: "APICULTURA Como EMPEZAR  🐝🧡🎥 Apicultura para PRINCIPIANTES. (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 4', youtubeId: 'YHctf7FIDf8' },
        { id: 'v98', title: "Puedo tener mis COLMENAS en CASA ?  🐝🧡🎥 Aquí podras descubrirlo! (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 5', youtubeId: 'VUiw5lgFVCA' },
        { id: 'v99', title: "The 40-Day Rule 🐝🧡🎥 Beekeeping for Beginners (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 6', youtubeId: 'Eon2Ui9DxlA' },
        { id: 'v100', title: "EXCLUIDOR de REINA  🐝🧡🎥 Si o No ??? (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 7', youtubeId: '9hHKmmtNN-Q' },
        { id: 'v101', title: "Como ENCENDER el AHUMADOR  🐝🧡🎥 Apicultura para PRINCIPIANTES (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 8', youtubeId: 'jr81ZYehFxc' },
        { id: 'v102', title: "Colmena ZANGANERA 🐝🧡🎥Que es ? (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 9', youtubeId: 'ghJo8FUMzUQ' },
        { id: 'v103', title: "Desbloquear COLMENA 🐝🧡🎥 Ampliar cámara de cría (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 10', youtubeId: 'aGgbbWBdtD0' },
        { id: 'v104', title: "Vertical Beehive by Hugo Negrioli 🐝🧡🎥 Beekeeping for Beginners (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 11', youtubeId: 'N0B5biIkyCc' },
        { id: 'v105', title: "VARROA  🐝🧡🎥 Que es la Varroasis ? (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 12', youtubeId: 'iCXwYe35Mc8' },
        { id: 'v106', title: "LARVA de ABEJA  🐝🧡🎥 Apicultura para PRINCIPIANTES (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 13', youtubeId: 'cgMpHr2aDS4' },
        { id: 'v107', title: "Beekeeping for Beginners 🐝🧡🎥 Introduction to Queen Bee Breeding (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 14', youtubeId: '2WtdMOfnT_A' },
        { id: 'v108', title: "CURSO de APICULTURA 🐝🧡🎥 APICULTURA para PRINCIPIANTES (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 15', youtubeId: 'tjn7FGcTVT0' },
        { id: 'v109', title: "Golden Rule in Beekeeping 🐝🧡🎥 The Best Tip for the Beekeeper (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 16', youtubeId: 'TcqQ8ycFt3E' },
        { id: 'v110', title: "POLILLA de la CERA  🐝🧡🎥 Destrucción de COLMENA! (Idioma: Espanhol)", duration: 'Apicultura (Espanhol) - Vídeo 17', youtubeId: 'Ar8iyj1jBL4' }
    ],

        books: [
        {
            id: "b1",
            title: "Manual de Criação de Rainhas",
            description: "Aprenda as técnicas detalhadas para a criação de rainhas autóctones em Portugal, garantindo a produtividade e a saúde das suas colónias.",
            badgeText: "LIVRO 1",
            badgeColor: "#E5A817",
            features: [
                "Criação de rainhas autóctones",
                "Gestão de apiários de fecundação",
                "Melhoramento genético de abelhas"
            ],
            downloadUrl: "materials/manual_criacao_rainhas.pdf",
            coverImage: "assets/covers/manual_rainhas.png",
            buttonText: "Descarregar livro"
        },
        {
            id: "b2",
            title: "Manual Técnico de Apicultura",
            description: "Um manual técnico completo com conceitos de biologia, anatomia e fisiologia das abelhas, equipamentos essenciais e as bases para a apicultura contemporânea.",
            badgeText: "LIVRO 2",
            badgeColor: "#6B8F3C",
            features: [
                "Biologia e comportamento da Apis",
                "Padrão de colmeia Langstroth",
                "Equipamentos de segurança e manejo"
            ],
            downloadUrl: "materials/manual_tecnico_apicultura.pdf",
            coverImage: "assets/covers/manual_tecnico.png",
            buttonText: "Descarregar livro"
        },
        {
            id: "b3",
            title: "Como Iniciar o Seu Empreendimento Apícola",
            description: "Dê o pontapé inicial na sua atividade apícola profissional. Um plano de negócios passo a passo para faturar alto com o mel.",
            badgeText: "LIVRO 3",
            badgeColor: "#B45309",
            features: [
                "Plano de negócios completo",
                "Viabilidade económico-financeira",
                "Estratégia de vendas de mel"
            ],
            downloadUrl: "materials/empreendimento_apicola.pdf",
            coverImage: "assets/covers/empreendimento_apicola.png",
            buttonText: "Descarregar livro"
        },
        {
            id: "b4",
            title: "Montagem e Registo de Apiário",
            description: "Instale e registe corretamente o seu apiário. Aprenda sobre conforto biológico, pasto apícola, relevo, água e segurança para obter superprodução.",
            badgeText: "LIVRO 4",
            badgeColor: "#059669",
            features: [
                "Instalação do apiário passo a passo",
                "Conforto biológico das abelhas",
                "Registo sanitário e de rebanho"
            ],
            downloadUrl: "materials/montagem_e_registo_apiario.pdf",
            coverImage: "assets/covers/montagem_registo_apiario.png",
            buttonText: "Descarregar livro"
        },
        {
            id: "b5",
            title: "Manual de Mapeamento Apícola",
            description: "Aprenda a realizar o mapeamento apícola da sua propriedade por satélite. Estude a flora melífera e determine a capacidade do seu apiário.",
            badgeText: "LIVRO 5",
            badgeColor: "#8B5CF6",
            features: [
                "Mapeamento por satélite (GPS)",
                "Cálculo de colmeias por hectare",
                "Identificação de flora melífera"
            ],
            downloadUrl: "materials/mapeamento_apicola.pdf",
            coverImage: "assets/covers/mapeamento_apicola.png",
            buttonText: "Descarregar livro"
        },
        {
            id: "b6",
            title: "O Grande Livro do Hidromel",
            description: "Explore 60 receitas detalhadas e tradicionais para fabricar o seu próprio hidromel artesanal em casa com diferentes tipos de mel.",
            badgeText: "LIVRO 6",
            badgeColor: "#EC4899",
            features: [
                "60 receitas detalhadas de hidromel",
                "Tipos de mel e variações de sabor",
                "Processos de fermentação e maturação"
            ],
            downloadUrl: "materials/grande_livro_hidromel.pdf",
            coverImage: "assets/covers/grande_livro_hidromel.png",
            buttonText: "Descarregar livro"
        }
    ],

    otherProducts: []
};
