import os

translations = {
    "fr": {
        "A must-have for anyone interested in bees.": "Un incontournable pour tous ceux qui s'intéressent aux abeilles.",
        "I almost spent hundreds on the wrong equipment before reading this. The gear guide alone is worth the price. I feel so much more confident handling my bees now.": "J'ai failli dépenser des centaines de dollars dans le mauvais équipement avant de lire ceci. Le guide du matériel vaut à lui seul le prix. Je me sens beaucoup plus en confiance pour m'occuper de mes abeilles maintenant.",
        "I was terrified of getting stung and making mistakes, but this bundle broke everything down so simply. My first hive is thriving, and I'm already planning to add a second one!": "J'étais terrifié à l'idée de me faire piquer et de faire des erreurs, mais ce pack a tout expliqué si simplement. Ma première ruche est florissante et je prévois déjà d'en ajouter une deuxième !",
        "Incredible resource for beginners.": "Ressource incroyable pour les débutants.",
        "Not only did I learn how to properly care for my bees, but the bonus on making mead at home was a huge plus. We are already enjoying our first batch!": "Non seulement j'ai appris à bien m'occuper de mes abeilles, mais le bonus sur la fabrication de l'hydromel à la maison était un énorme plus. Nous profitons déjà de notre premier lot !",
        "Saved me so much money and time.": "M'a fait gagner tellement d'argent et de temps.",
        "The bonus mead guide is fantastic!": "Le guide bonus sur l'hydromel est fantastique !",
        "The step-by-step first year guide is exactly what I needed. It takes all the guesswork out of beekeeping. Highly recommend to anyone wanting to start this hobby.": "Le guide étape par étape de la première année est exactement ce dont j'avais besoin. Il élimine toutes les incertitudes de l'apiculture. Je le recommande vivement à tous ceux qui souhaitent se lancer dans ce passe-temps.",
        "A complete beginner’s guide to making your own mead": "Un guide complet pour les débutants pour fabriquer votre propre hydromel",
        "A complete step-by-step first-year plan": "Un plan complet étape par étape pour la première année",
        "A proven step-by-step path": "Un chemin éprouvé étape par étape",
        "And even the thrill of making your own mead": "Et même le frisson de fabriquer votre propre hydromel",
        "Are you dreaming of starting your own backyard beehive, but feel overwhelmed by the fear of messing everything up?": "Rêvez-vous de créer votre propre ruche de jardin, mais vous sentez-vous submergé par la peur de tout gâcher ?",
        "BUY 1 GET 3": "ACHETEZ 1 OBTENEZ 3",
        "BUY NOW": "ACHETER MAINTENANT",
        "Backyard beekeeping best practices": "Meilleures pratiques de l'apiculture de jardin",
        "Because the truth is:": "Parce que la vérité est :",
        "Because we manage everything directly — from printing to fulfillment — we can skip retail markups and offer the entire bundle (normally $59.70) for only $19.90.": "Parce que nous gérons tout directement — de l'impression à l'exécution — nous pouvons éviter les marges de vente au détail et offrir le pack complet (normalement 59,70 $) pour seulement 19,90 $.",
        "Beekeeping Projects": "Projets Apicoles",
        "Beekeeping doesn’t have to be confusing. It can be simple, joyful, and deeply rewarding… when you start with the right guidance.": "L'apiculture ne doit pas être compliquée. Cela peut être simple, joyeux et profondément gratifiant... lorsque vous commencez avec les bons conseils.",
        "Beekeeping for Beginners + 2 BONUSES": "L'Apiculture pour les Débutants + 2 BONUS",
        "Beekeeping only feels hard when you try to piece together random YouTube videos, outdated tips, and contradictory advice. That’s when mistakes happen — dead colonies, wasted money, stings, frustration, and dreams abandoned.": "L'apiculture ne semble difficile que lorsque vous essayez de rassembler des vidéos YouTube aléatoires, des conseils obsolètes et des avis contradictoires. C'est à ce moment-là que des erreurs se produisent — colonies mortes, argent gaspillé, piqûres, frustration et rêves abandonnés.",
        "But with the right foundation, beekeeping becomes simple, safe, and incredibly": "Mais avec les bonnes bases, l'apiculture devient simple, sûre et incroyablement",
        "Clarity": "Clarté",
        "Confidence": "Confiance",
        "Contact Us": "Contactez-nous",
        "FINAL HOURS – 70% OFF ENDS IN": "DERNIÈRES HEURES – 70% DE RÉDUCTION SE TERMINE DANS",
        "For a limited time only, here is what you’ll get:": "Pour un temps limité seulement, voici ce que vous obtiendrez :",
        "Grab your 70% OFF bundle today and finally become the beekeeper you’ve always wanted to be.": "Saisissez votre pack à 70 % de réduction aujourd'hui et devenez enfin l'apiculteur que vous avez toujours voulu être.",
        "Here’s What People Are Saying About Us": "Voici ce que les gens disent de nous",
        "Here’s the simple truth: once a year, around this season, we run a special Reader Event to thank our audience and make our most popular collections easier to access.": "Voici la simple vérité : une fois par an, vers cette saison, nous organisons un événement spécial pour les lecteurs afin de remercier notre public et de rendre nos collections les plus populaires plus faciles d'accès.",
        "Honey harvesting methods": "Méthodes de récolte du miel",
        "How to choose the right hive, tools, and bee species": "Comment choisir la bonne ruche, les outils et l'espèce d'abeille",
        "How to inspect your hive confidently": "Comment inspecter votre ruche en toute confiance",
        "If you’ve been wanting to start beekeeping but felt overwhelmed, unsure, or scared of doing something wrong, this bundle removes every obstacle in your way.": "Si vous vouliez commencer l'apiculture mais que vous vous sentiez dépassé, incertain ou effrayé de faire quelque chose de mal, ce pack élimine tous les obstacles sur votre chemin.",
        "Inside the Bundle You’ll Discover:": "À l'intérieur du pack, vous découvrirez :",
        "It gives you:": "Il vous donne :",
        "Order now": "Commandez maintenant",
        "Right now, while it’s": "En ce moment, alors qu'il est",
        "Skip to content": "Passer au contenu",
        "That’s exactly why this": "C'est exactement pourquoi ce",
        "The joy of producing your own honey": "La joie de produire votre propre miel",
        "This bundle doesn’t just teach you beekeeping —": "Ce pack ne vous enseigne pas seulement l'apiculture —",
        "Thousands of beginners feel excited about beekeeping… until they realize they have no idea where to start, what equipment to buy, or how to keep their bees healthy and productive.": "Des milliers de débutants sont enthousiasmés par l'apiculture... jusqu'à ce qu'ils réalisent qu'ils n'ont aucune idée par où commencer, quel équipement acheter ou comment garder leurs abeilles en bonne santé et productives.",
        "Tools to avoid beginner mistakes": "Des outils pour éviter les erreurs de débutant",
        "We get it — three bestselling books for the price of one isn’t something you see every day.": "Nous comprenons — trois livres à succès pour le prix d'un, ce n'est pas quelque chose que l'on voit tous les jours.",
        "What if the only thing standing between you and a thriving hive is the right step-by-step guidance?": "Et si la seule chose qui vous séparait d'une ruche florissante était les bons conseils étape par étape ?",
        "When the event ends, prices return to normal.": "Lorsque l'événement se termine, les prix reviennent à la normale.",
        "Why does this offer sound too good to be true?": "Pourquoi cette offre semble-t-elle trop belle pour être vraie ?",
        "Why wait?": "Pourquoi attendre ?",
        "You Save 70%": "Vous Économisez 70%",
        "You just need a clear, beginner-friendly roadmap that takes you from confusion to confidence.": "Vous avez juste besoin d'une feuille de route claire et conviviale pour les débutants qui vous fait passer de la confusion à la confiance.",
        "You’re not alone.": "Vous n'êtes pas seul.",
        "a deal that won’t last. Instant direct digital download (After you complete the payment you will immediately have the option to download the product(s) from the final purchase page and you will also receive a download email shortly after).": "une offre qui ne durera pas. Téléchargement numérique direct et instantané (Après avoir effectué le paiement, vous aurez immédiatement la possibilité de télécharger le(s) produit(s) à partir de la page d'achat finale et vous recevrez également un e-mail de téléchargement peu de temps après).",
        "and save 70% before this limited-time deal disappears.": "et économisez 70 % avant que cette offre d'une durée limitée ne disparaisse.",
        "for clean, safe, delicious results": "pour des résultats propres, sûrs et délicieux",
        "for small spaces": "pour les petits espaces",
        "it makes you fall in love with it.": "cela vous fait en tomber amoureux.",
        "rewarding.": "gratifiant.",
        "so you always know exactly what to do": "pour que vous sachiez toujours exactement quoi faire",
        "three complete guides for the price of one —": "trois guides complets pour le prix d'un —",
        "using the included inspection checklist": "en utilisant la liste de contrôle d'inspection incluse",
        "was created: to walk you step-by-step from your very first hive setup to harvesting honey, preventing disease, raising strong colonies, and even crafting your own homemade mead.": "a été créé : pour vous guider pas à pas depuis votre toute première installation de ruche jusqu'à la récolte du miel, la prévention des maladies, l'élevage de colonies fortes, et même la fabrication de votre propre hydromel maison.",
        "with simple recipes": "avec des recettes simples",
        "without overspending": "sans trop dépenser",
        "you don’t need experience. You don’t need special skills.": "vous n'avez pas besoin d'expérience. Vous n'avez pas besoin de compétences particulières.",
        "3-Book Bundle": "Pack de 3 Livres"
    },
    "it": {
        "A must-have for anyone interested in bees.": "Un must per chiunque sia interessato alle api.",
        "I almost spent hundreds on the wrong equipment before reading this. The gear guide alone is worth the price. I feel so much more confident handling my bees now.": "Ho quasi speso centinaia di dollari nell'attrezzatura sbagliata prima di leggere questo. La guida all'attrezzatura da sola vale il prezzo. Mi sento molto più sicuro nel gestire le mie api ora.",
        "I was terrified of getting stung and making mistakes, but this bundle broke everything down so simply. My first hive is thriving, and I'm already planning to add a second one!": "Ero terrorizzato all'idea di essere punto e di fare errori, ma questo pacchetto ha spiegato tutto in modo così semplice. La mia prima arnia è fiorente e sto già pianificando di aggiungerne una seconda!",
        "Incredible resource for beginners.": "Risorsa incredibile per i principianti.",
        "Not only did I learn how to properly care for my bees, but the bonus on making mead at home was a huge plus. We are already enjoying our first batch!": "Non solo ho imparato a prendermi cura delle mie api, ma il bonus su come fare l'idromele in casa è stato un enorme vantaggio. Stiamo già gustando il nostro primo lotto!",
        "Saved me so much money and time.": "Mi ha fatto risparmiare un sacco di soldi e tempo.",
        "The bonus mead guide is fantastic!": "La guida bonus sull'idromele è fantastica!",
        "The step-by-step first year guide is exactly what I needed. It takes all the guesswork out of beekeeping. Highly recommend to anyone wanting to start this hobby.": "La guida passo dopo passo per il primo anno è esattamente ciò di cui avevo bisogno. Elimina ogni incertezza nell'apicoltura. Lo consiglio vivamente a chiunque voglia iniziare questo hobby.",
        "A complete beginner’s guide to making your own mead": "Una guida completa per principianti per fare il tuo idromele",
        "A complete step-by-step first-year plan": "Un piano completo passo dopo passo per il primo anno",
        "A proven step-by-step path": "Un percorso provato passo dopo passo",
        "And even the thrill of making your own mead": "E persino l'emozione di fare il tuo idromele",
        "Are you dreaming of starting your own backyard beehive, but feel overwhelmed by the fear of messing everything up?": "Sogni di avviare il tuo alveare in giardino, ma ti senti sopraffatto dalla paura di rovinare tutto?",
        "BUY 1 GET 3": "COMPRA 1 PRENDI 3",
        "BUY NOW": "ACQUISTA ORA",
        "Backyard beekeeping best practices": "Migliori pratiche per l'apicoltura da cortile",
        "Because the truth is:": "Perché la verità è:",
        "Because we manage everything directly — from printing to fulfillment — we can skip retail markups and offer the entire bundle (normally $59.70) for only $19.90.": "Poiché gestiamo tutto direttamente, dalla stampa alla spedizione, possiamo evitare i ricarichi al dettaglio e offrire l'intero pacchetto (normalmente $ 59,70) per soli $ 19,90.",
        "Beekeeping Projects": "Progetti di Apicoltura",
        "Beekeeping doesn’t have to be confusing. It can be simple, joyful, and deeply rewarding… when you start with the right guidance.": "L'apicoltura non deve essere confusa. Può essere semplice, gioiosa e profondamente gratificante... quando inizi con la giusta guida.",
        "Beekeeping for Beginners + 2 BONUSES": "Apicoltura per Principianti + 2 BONUS",
        "Beekeeping only feels hard when you try to piece together random YouTube videos, outdated tips, and contradictory advice. That’s when mistakes happen — dead colonies, wasted money, stings, frustration, and dreams abandoned.": "L'apicoltura sembra difficile solo quando cerchi di mettere insieme video di YouTube a caso, suggerimenti obsoleti e consigli contraddittori. È allora che accadono gli errori: colonie morte, soldi sprecati, punture, frustrazione e sogni abbandonati.",
        "But with the right foundation, beekeeping becomes simple, safe, and incredibly": "Ma con le giuste fondamenta, l'apicoltura diventa semplice, sicura e incredibilmente",
        "Clarity": "Chiarezza",
        "Confidence": "Fiducia",
        "Contact Us": "Contattaci",
        "FINAL HOURS – 70% OFF ENDS IN": "ULTIME ORE – LO SCONTO DEL 70% TERMINA IN",
        "For a limited time only, here is what you’ll get:": "Solo per un periodo limitato, ecco cosa otterrai:",
        "Grab your 70% OFF bundle today and finally become the beekeeper you’ve always wanted to be.": "Prendi il tuo pacchetto con il 70% di sconto oggi e diventa finalmente l'apicoltore che hai sempre desiderato essere.",
        "Here’s What People Are Saying About Us": "Ecco cosa dicono le persone di noi",
        "Here’s the simple truth: once a year, around this season, we run a special Reader Event to thank our audience and make our most popular collections easier to access.": "Ecco la semplice verità: una volta all'anno, in questa stagione, organizziamo uno speciale Reader Event per ringraziare il nostro pubblico e rendere più facile l'accesso alle nostre collezioni più popolari.",
        "Honey harvesting methods": "Metodi di raccolta del miele",
        "How to choose the right hive, tools, and bee species": "Come scegliere la giusta arnia, gli strumenti e le specie di api",
        "How to inspect your hive confidently": "Come ispezionare la tua arnia con sicurezza",
        "If you’ve been wanting to start beekeeping but felt overwhelmed, unsure, or scared of doing something wrong, this bundle removes every obstacle in your way.": "Se volevi iniziare l'apicoltura ma ti sentivi sopraffatto, insicuro o spaventato di fare qualcosa di sbagliato, questo pacchetto rimuove ogni ostacolo sul tuo cammino.",
        "Inside the Bundle You’ll Discover:": "All'interno del pacchetto scoprirai:",
        "It gives you:": "Ti dà:",
        "Order now": "Ordina ora",
        "Right now, while it’s": "In questo momento, mentre è",
        "Skip to content": "Salta al contenuto",
        "That’s exactly why this": "Questo è esattamente il motivo per cui questo",
        "The joy of producing your own honey": "La gioia di produrre il tuo miele",
        "This bundle doesn’t just teach you beekeeping —": "Questo pacchetto non ti insegna solo l'apicoltura —",
        "Thousands of beginners feel excited about beekeeping… until they realize they have no idea where to start, what equipment to buy, or how to keep their bees healthy and productive.": "Migliaia di principianti si sentono entusiasti dell'apicoltura... finché non si rendono conto che non hanno idea di dove iniziare, quale attrezzatura comprare o come mantenere le loro api sane e produttive.",
        "Tools to avoid beginner mistakes": "Strumenti per evitare gli errori dei principianti",
        "We get it — three bestselling books for the price of one isn’t something you see every day.": "Lo capiamo — tre libri bestseller al prezzo di uno non sono qualcosa che si vede tutti i giorni.",
        "What if the only thing standing between you and a thriving hive is the right step-by-step guidance?": "E se l'unica cosa tra te e un'arnia fiorente fosse la giusta guida passo dopo passo?",
        "When the event ends, prices return to normal.": "Quando l'evento finisce, i prezzi tornano alla normalità.",
        "Why does this offer sound too good to be true?": "Perché questa offerta sembra troppo bella per essere vera?",
        "Why wait?": "Perché aspettare?",
        "You Save 70%": "Risparmi il 70%",
        "You just need a clear, beginner-friendly roadmap that takes you from confusion to confidence.": "Hai solo bisogno di una tabella di marcia chiara e adatta ai principianti che ti porti dalla confusione alla sicurezza.",
        "You’re not alone.": "Non sei solo.",
        "a deal that won’t last. Instant direct digital download (After you complete the payment you will immediately have the option to download the product(s) from the final purchase page and you will also receive a download email shortly after).": "un affare che non durerà. Download digitale diretto e istantaneo (Dopo aver completato il pagamento avrai immediatamente la possibilità di scaricare il/i prodotto/i dalla pagina di acquisto finale e riceverai anche un'e-mail di download poco dopo).",
        "and save 70% before this limited-time deal disappears.": "e risparmia il 70% prima che questa offerta a tempo limitato scompaia.",
        "for clean, safe, delicious results": "per risultati puliti, sicuri e deliziosi",
        "for small spaces": "per piccoli spazi",
        "it makes you fall in love with it.": "ti fa innamorare di esso.",
        "rewarding.": "gratificante.",
        "so you always know exactly what to do": "così sai sempre esattamente cosa fare",
        "three complete guides for the price of one —": "tre guide complete al prezzo di una —",
        "using the included inspection checklist": "usando la lista di controllo di ispezione inclusa",
        "was created: to walk you step-by-step from your very first hive setup to harvesting honey, preventing disease, raising strong colonies, and even crafting your own homemade mead.": "è stato creato: per guidarti passo dopo passo dalla tua prima installazione dell'arnia alla raccolta del miele, prevenendo le malattie, allevando colonie forti e persino creando il tuo idromele fatto in casa.",
        "with simple recipes": "con ricette semplici",
        "without overspending": "senza spendere troppo",
        "you don’t need experience. You don’t need special skills.": "non hai bisogno di esperienza. Non hai bisogno di abilità speciali.",
        "3-Book Bundle": "Pacchetto di 3 Libri"
    },
    "es": {
        "A must-have for anyone interested in bees.": "Un imprescindible para cualquier persona interesada en las abejas.",
        "I almost spent hundreds on the wrong equipment before reading this. The gear guide alone is worth the price. I feel so much more confident handling my bees now.": "Casi gasto cientos en el equipo equivocado antes de leer esto. La guía de equipo por sí sola vale el precio. Me siento mucho más seguro manejando a mis abejas ahora.",
        "I was terrified of getting stung and making mistakes, but this bundle broke everything down so simply. My first hive is thriving, and I'm already planning to add a second one!": "Me aterrorizaba que me picaran y cometer errores, pero este paquete desglosó todo de manera muy sencilla. ¡Mi primera colmena está prosperando y ya estoy planeando agregar una segunda!",
        "Incredible resource for beginners.": "Recurso increíble para principiantes.",
        "Not only did I learn how to properly care for my bees, but the bonus on making mead at home was a huge plus. We are already enjoying our first batch!": "No solo aprendí cómo cuidar adecuadamente a mis abejas, sino que el bono sobre cómo hacer hidromiel en casa fue una gran ventaja. ¡Ya estamos disfrutando de nuestro primer lote!",
        "Saved me so much money and time.": "Me ahorró mucho dinero y tiempo.",
        "The bonus mead guide is fantastic!": "¡La guía de hidromiel extra es fantástica!",
        "The step-by-step first year guide is exactly what I needed. It takes all the guesswork out of beekeeping. Highly recommend to anyone wanting to start this hobby.": "La guía paso a paso del primer año es exactamente lo que necesitaba. Elimina todas las conjeturas de la apicultura. Lo recomiendo encarecidamente a cualquiera que quiera empezar en este pasatiempo.",
        "A complete beginner’s guide to making your own mead": "Una guía completa para principiantes para hacer tu propio hidromiel",
        "A complete step-by-step first-year plan": "Un plan completo paso a paso para el primer año",
        "A proven step-by-step path": "Un camino probado paso a paso",
        "And even the thrill of making your own mead": "E incluso la emoción de hacer tu propio hidromiel",
        "Are you dreaming of starting your own backyard beehive, but feel overwhelmed by the fear of messing everything up?": "¿Sueñas con comenzar tu propia colmena en el patio trasero, pero te sientes abrumado por el miedo a estropear todo?",
        "BUY 1 GET 3": "COMPRA 1 LLEVA 3",
        "BUY NOW": "COMPRAR AHORA",
        "Backyard beekeeping best practices": "Mejores prácticas de apicultura de patio",
        "Because the truth is:": "Porque la verdad es:",
        "Because we manage everything directly — from printing to fulfillment — we can skip retail markups and offer the entire bundle (normally $59.70) for only $19.90.": "Debido a que gestionamos todo directamente, desde la impresión hasta el cumplimiento, podemos omitir los márgenes minoristas y ofrecer el paquete completo (normalmente $59.70) por solo $19.90.",
        "Beekeeping Projects": "Proyectos de Apicultura",
        "Beekeeping doesn’t have to be confusing. It can be simple, joyful, and deeply rewarding… when you start with the right guidance.": "La apicultura no tiene por qué ser confusa. Puede ser simple, alegre y profundamente gratificante... cuando comienzas con la orientación adecuada.",
        "Beekeeping for Beginners + 2 BONUSES": "Apicultura para Principiantes + 2 BONOS",
        "Beekeeping only feels hard when you try to piece together random YouTube videos, outdated tips, and contradictory advice. That’s when mistakes happen — dead colonies, wasted money, stings, frustration, and dreams abandoned.": "La apicultura solo parece difícil cuando intentas juntar videos aleatorios de YouTube, consejos desactualizados y sugerencias contradictorias. Ahí es cuando ocurren los errores: colonias muertas, dinero desperdiciado, picaduras, frustración y sueños abandonados.",
        "But with the right foundation, beekeeping becomes simple, safe, and incredibly": "Pero con la base adecuada, la apicultura se vuelve simple, segura e increíblemente",
        "Clarity": "Claridad",
        "Confidence": "Confianza",
        "Contact Us": "Contáctenos",
        "FINAL HOURS – 70% OFF ENDS IN": "ÚLTIMAS HORAS – 70% DE DESCUENTO TERMINA EN",
        "For a limited time only, here is what you’ll get:": "Solo por tiempo limitado, esto es lo que obtendrás:",
        "Grab your 70% OFF bundle today and finally become the beekeeper you’ve always wanted to be.": "Obtén tu paquete con un 70% de descuento hoy y finalmente conviértete en el apicultor que siempre has querido ser.",
        "Here’s What People Are Saying About Us": "Esto es lo que dice la gente sobre nosotros",
        "Here’s the simple truth: once a year, around this season, we run a special Reader Event to thank our audience and make our most popular collections easier to access.": "Aquí está la simple verdad: una vez al año, en esta temporada, organizamos un evento especial para lectores para agradecer a nuestra audiencia y hacer que nuestras colecciones más populares sean más accesibles.",
        "Honey harvesting methods": "Métodos de cosecha de miel",
        "How to choose the right hive, tools, and bee species": "Cómo elegir la colmena, las herramientas y las especies de abejas adecuadas",
        "How to inspect your hive confidently": "Cómo inspeccionar su colmena con confianza",
        "If you’ve been wanting to start beekeeping but felt overwhelmed, unsure, or scared of doing something wrong, this bundle removes every obstacle in your way.": "Si ha querido comenzar a practicar la apicultura pero se sintió abrumado, inseguro o asustado de hacer algo mal, este paquete elimina todos los obstáculos en su camino.",
        "Inside the Bundle You’ll Discover:": "Dentro del paquete descubrirás:",
        "It gives you:": "Te da:",
        "Order now": "Pide ahora",
        "Right now, while it’s": "En este momento, mientras está",
        "Skip to content": "Saltar al contenido",
        "That’s exactly why this": "Es exactamente por eso que este",
        "The joy of producing your own honey": "La alegría de producir tu propia miel",
        "This bundle doesn’t just teach you beekeeping —": "Este paquete no solo le enseña apicultura —",
        "Thousands of beginners feel excited about beekeeping… until they realize they have no idea where to start, what equipment to buy, or how to keep their bees healthy and productive.": "Miles de principiantes se sienten emocionados con la apicultura... hasta que se dan cuenta de que no tienen idea de dónde empezar, qué equipo comprar o cómo mantener sus abejas sanas y productivas.",
        "Tools to avoid beginner mistakes": "Herramientas para evitar errores de principiantes",
        "We get it — three bestselling books for the price of one isn’t something you see every day.": "Lo entendemos — tres libros superventas por el precio de uno no es algo que se vea todos los días.",
        "What if the only thing standing between you and a thriving hive is the right step-by-step guidance?": "¿Qué pasa si lo único que se interpone entre usted y una colmena próspera es la guía correcta paso a paso?",
        "When the event ends, prices return to normal.": "Cuando termina el evento, los precios vuelven a la normalidad.",
        "Why does this offer sound too good to be true?": "¿Por qué esta oferta parece demasiado buena para ser verdad?",
        "Why wait?": "¿Por qué esperar?",
        "You Save 70%": "Ahorras un 70%",
        "You just need a clear, beginner-friendly roadmap that takes you from confusion to confidence.": "Solo necesita una hoja de ruta clara y amigable para principiantes que lo lleve de la confusión a la confianza.",
        "You’re not alone.": "No estás solo.",
        "a deal that won’t last. Instant direct digital download (After you complete the payment you will immediately have the option to download the product(s) from the final purchase page and you will also receive a download email shortly after).": "una oferta que no durará. Descarga digital directa instantánea (Después de completar el pago, tendrá inmediatamente la opción de descargar los productos de la página de compra final y también recibirá un correo electrónico de descarga poco después).",
        "and save 70% before this limited-time deal disappears.": "y ahorra un 70% antes de que esta oferta por tiempo limitado desaparezca.",
        "for clean, safe, delicious results": "para resultados limpios, seguros y deliciosos",
        "for small spaces": "para espacios pequeños",
        "it makes you fall in love with it.": "te hace enamorarte de ella.",
        "rewarding.": "gratificante.",
        "so you always know exactly what to do": "para que siempre sepas exactamente qué hacer",
        "three complete guides for the price of one —": "tres guías completas por el precio de una —",
        "using the included inspection checklist": "usando la lista de verificación de inspección incluida",
        "was created: to walk you step-by-step from your very first hive setup to harvesting honey, preventing disease, raising strong colonies, and even crafting your own homemade mead.": "fue creado: para guiarlo paso a paso desde su primera configuración de colmena hasta la recolección de miel, la prevención de enfermedades, la cría de colonias fuertes e incluso la elaboración de su propio hidromiel casero.",
        "with simple recipes": "con recetas simples",
        "without overspending": "sin gastar de más",
        "you don’t need experience. You don’t need special skills.": "no necesitas experiencia. No necesitas habilidades especiales.",
        "3-Book Bundle": "Paquete de 3 Libros"
    },
    "pt": {
        "A must-have for anyone interested in bees.": "Um item obrigatório para qualquer pessoa interessada em abelhas.",
        "I almost spent hundreds on the wrong equipment before reading this. The gear guide alone is worth the price. I feel so much more confident handling my bees now.": "Quase gastei centenas no equipamento errado antes de ler isso. O guia de equipamentos por si só vale o preço. Sinto-me muito mais confiante lidando com minhas abelhas agora.",
        "I was terrified of getting stung and making mistakes, but this bundle broke everything down so simply. My first hive is thriving, and I'm already planning to add a second one!": "Eu estava aterrorizado de ser picado e cometer erros, mas este pacote explicou tudo de forma tão simples. Minha primeira colmeia está prosperando, e já estou planejando adicionar uma segunda!",
        "Incredible resource for beginners.": "Recurso incrível para iniciantes.",
        "Not only did I learn how to properly care for my bees, but the bonus on making mead at home was a huge plus. We are already enjoying our first batch!": "Não só aprendi como cuidar adequadamente das minhas abelhas, mas o bônus sobre como fazer hidromiel em casa foi uma grande vantagem. Já estamos aproveitando nosso primeiro lote!",
        "Saved me so much money and time.": "Me economizou muito dinheiro e tempo.",
        "The bonus mead guide is fantastic!": "O guia bônus de hidromel é fantástico!",
        "The step-by-step first year guide is exactly what I needed. It takes all the guesswork out of beekeeping. Highly recommend to anyone wanting to start this hobby.": "O guia passo a passo do primeiro ano é exatamente o que eu precisava. Ele elimina todas as adivinhações da apicultura. Recomendo fortemente a quem deseja iniciar este hobby.",
        "A complete beginner’s guide to making your own mead": "Um guia completo para iniciantes para fazer seu próprio hidromel",
        "A complete step-by-step first-year plan": "Um plano completo passo a passo para o primeiro ano",
        "A proven step-by-step path": "Um caminho comprovado passo a passo",
        "And even the thrill of making your own mead": "E até mesmo a emoção de fazer seu próprio hidromel",
        "Are you dreaming of starting your own backyard beehive, but feel overwhelmed by the fear of messing everything up?": "Você sonha em começar sua própria colmeia no quintal, mas se sente sobrecarregado pelo medo de estragar tudo?",
        "BUY 1 GET 3": "COMPRE 1 LEVE 3",
        "BUY NOW": "COMPRAR AGORA",
        "Backyard beekeeping best practices": "Melhores práticas de apicultura de quintal",
        "Because the truth is:": "Porque a verdade é:",
        "Because we manage everything directly — from printing to fulfillment — we can skip retail markups and offer the entire bundle (normally $59.70) for only $19.90.": "Como gerenciamos tudo diretamente — desde a impressão até o atendimento — podemos evitar as margens de lucro do varejo e oferecer o pacote inteiro (normalmente $ 59,70) por apenas $ 19,90.",
        "Beekeeping Projects": "Projetos de Apicultura",
        "Beekeeping doesn’t have to be confusing. It can be simple, joyful, and deeply rewarding… when you start with the right guidance.": "A apicultura não precisa ser confusa. Pode ser simples, alegre e profundamente gratificante... quando você começa com a orientação certa.",
        "Beekeeping for Beginners + 2 BONUSES": "Apicultura para Iniciantes + 2 BÔNUS",
        "Beekeeping only feels hard when you try to piece together random YouTube videos, outdated tips, and contradictory advice. That’s when mistakes happen — dead colonies, wasted money, stings, frustration, and dreams abandoned.": "A apicultura só parece difícil quando você tenta juntar vídeos aleatórios do YouTube, dicas desatualizadas e conselhos contraditórios. É aí que os erros acontecem — colônias mortas, dinheiro desperdiçado, picadas, frustração e sonhos abandonados.",
        "But with the right foundation, beekeeping becomes simple, safe, and incredibly": "Mas com a base certa, a apicultura se torna simples, segura e incrivelmente",
        "Clarity": "Clareza",
        "Confidence": "Confiança",
        "Contact Us": "Contate-nos",
        "FINAL HOURS – 70% OFF ENDS IN": "ÚLTIMAS HORAS – 70% DE DESCONTO TERMINA EM",
        "For a limited time only, here is what you’ll get:": "Apenas por tempo limitado, aqui está o que você vai receber:",
        "Grab your 70% OFF bundle today and finally become the beekeeper you’ve always wanted to be.": "Garanta seu pacote com 70% de desconto hoje e finalmente torne-se o apicultor que você sempre quis ser.",
        "Here’s What People Are Saying About Us": "Aqui está o que as pessoas estão dizendo sobre nós",
        "Here’s the simple truth: once a year, around this season, we run a special Reader Event to thank our audience and make our most popular collections easier to access.": "Aqui está a simples verdade: uma vez por ano, nesta temporada, realizamos um Evento Especial do Leitor para agradecer ao nosso público e tornar nossas coleções mais populares mais fáceis de acessar.",
        "Honey harvesting methods": "Métodos de colheita de mel",
        "How to choose the right hive, tools, and bee species": "Como escolher a colmeia, as ferramentas e a espécie de abelha certas",
        "How to inspect your hive confidently": "Como inspecionar sua colmeia com confiança",
        "If you’ve been wanting to start beekeeping but felt overwhelmed, unsure, or scared of doing something wrong, this bundle removes every obstacle in your way.": "Se você queria começar a apicultura, mas se sentia sobrecarregado, inseguro ou com medo de fazer algo errado, este pacote remove todos os obstáculos em seu caminho.",
        "Inside the Bundle You’ll Discover:": "Dentro do pacote você descobrirá:",
        "It gives you:": "Isso lhe dá:",
        "Order now": "Peça agora",
        "Right now, while it’s": "Neste momento, enquanto está",
        "Skip to content": "Pular para o conteúdo",
        "That’s exactly why this": "É exatamente por isso que este",
        "The joy of producing your own honey": "A alegria de produzir seu próprio mel",
        "This bundle doesn’t just teach you beekeeping —": "Este pacote não ensina apenas a apicultura —",
        "Thousands of beginners feel excited about beekeeping… until they realize they have no idea where to start, what equipment to buy, or how to keep their bees healthy and productive.": "Milhares de iniciantes se sentem entusiasmados com a apicultura... até perceberem que não fazem ideia de onde começar, que equipamento comprar ou como manter suas abelhas saudáveis e produtivas.",
        "Tools to avoid beginner mistakes": "Ferramentas para evitar erros de iniciantes",
        "We get it — three bestselling books for the price of one isn’t something you see every day.": "Nós entendemos — três livros mais vendidos pelo preço de um não é algo que se vê todos os dias.",
        "What if the only thing standing between you and a thriving hive is the right step-by-step guidance?": "E se a única coisa entre você e uma colmeia próspera for a orientação passo a passo certa?",
        "When the event ends, prices return to normal.": "Quando o evento termina, os preços voltam ao normal.",
        "Why does this offer sound too good to be true?": "Por que esta oferta parece boa demais para ser verdade?",
        "Why wait?": "Por que esperar?",
        "You Save 70%": "Você Economiza 70%",
        "You just need a clear, beginner-friendly roadmap that takes you from confusion to confidence.": "Você só precisa de um roteiro claro e amigável para iniciantes que o leve da confusão à confiança.",
        "You’re not alone.": "Você não está sozinho.",
        "a deal that won’t last. Instant direct digital download (After you complete the payment you will immediately have the option to download the product(s) from the final purchase page and you will also receive a download email shortly after).": "um acordo que não vai durar. Download digital direto instantâneo (Após concluir o pagamento, você terá imediatamente a opção de baixar os produtos da página de compra final e também receberá um e-mail de download logo em seguida).",
        "and save 70% before this limited-time deal disappears.": "e economize 70% antes que esta oferta por tempo limitado desapareça.",
        "for clean, safe, delicious results": "para resultados limpos, seguros e deliciosos",
        "for small spaces": "para pequenos espaços",
        "it makes you fall in love with it.": "isso faz você se apaixonar por ela.",
        "rewarding.": "gratificante.",
        "so you always know exactly what to do": "para que você sempre saiba exatamente o que fazer",
        "three complete guides for the price of one —": "três guias completos pelo preço de um —",
        "using the included inspection checklist": "usando a lista de verificação de inspeção incluída",
        "was created: to walk you step-by-step from your very first hive setup to harvesting honey, preventing disease, raising strong colonies, and even crafting your own homemade mead.": "foi criado: para orientá-lo passo a passo desde sua primeira configuração de colmeia até a colheita de mel, prevenção de doenças, criação de colônias fortes e até mesmo a elaboração de seu próprio hidromel caseiro.",
        "with simple recipes": "com receitas simples",
        "without overspending": "sem gastar demais",
        "you don’t need experience. You don’t need special skills.": "você não precisa de experiência. Você não precisa de habilidades especiais.",
        "3-Book Bundle": "Pacote de 3 Livros"
    }
}

base_dir = "/Users/riansouza/Downloads/PRODUTOS 2"

for lang in ["fr", "it", "es", "pt"]:
    file_path = os.path.join(base_dir, f"bkp-{lang}", "index.html")
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Apply translations by replacing each string
    for eng, trans in translations[lang].items():
        # Using string replace, which is safer than bs4 rewriting
        content = content.replace(eng, trans)
        
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
        
print("All pages translated successfully!")
