try{document.documentElement.dataset.theme=localStorage.getItem('offervault-theme')||'dark';document.documentElement.dataset.sidebar=localStorage.getItem('offervault-sidebar')||'expanded';}catch{document.documentElement.dataset.theme='dark';}
const app=document.querySelector('#app'),modalRoot=document.querySelector('#modal-root');
const labels={idea:'Ideia',research:'Em pesquisa',approved:'Aprovado',active:'Ativo',archived:'Arquivado',todo:'Pendente',doing:'Em andamento',blocked:'Bloqueada',review:'Em revisão',done:'Concluída',production:'Produção',pilot:'Teste inicial',expansion:'Expansão',paused:'Pausado',preparing:'Preparação',ready:'Pronto para lançar',testing:'Em teste',running:'Rodando',pending:'Em andamento',validated:'Validado',not_validated:'Não validado'};
const langCatalog=[['de','Alemão'],['en','Inglês'],['fr','Francês'],['es','Espanhol'],['it','Italiano'],['nl','Holandês'],['sv','Sueco'],['da','Dinamarquês'],['no','Norueguês'],['fi','Finlandês'],['pl','Polonês'],['ro','Romeno'],['cs','Tcheco'],['hu','Húngaro'],['el','Grego'],['hr','Croata'],['sl','Esloveno'],['sk','Eslovaco'],['bg','Búlgaro'],['pt-br','Português'],['he','Hebraico'],['ja','Japonês'],['tr','Turco'],['ar','Árabe'],['uk','Ucraniano']];
const paths={grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',folder:'<path d="M3 7V5a2 2 0 0 1 2-2h5l3 4h6a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>',globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c5 5 5 13 0 18-5-5-5-13 0-18z"/>',check:'<path d="m5 12 4 4L19 6"/>',tasks:'<path d="m3 6 2 2 3-4M11 6h10m-18 8 2 2 3-4m3 2h10M3 21h18"/>',gamma:'<path d="M5 4h14M12 4v16m-4 0h8"/>',shop:'<path d="M4 9h16l-2-6H6zM5 9v12h14V9M9 21v-7h6v7"/>',users:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-16a3 3 0 0 1 0 6m3 10v-3a6 6 0 0 0-2-4"/>',plus:'<path d="M12 5v14M5 12h14"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',chevron:'<path d="m9 5 7 7-7 7"/>',search:'<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>',link:'<path d="m10 13 4-4m-6 7-2 2a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m4 0 2-2a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',file:'<path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6m-6 4h6"/>',edit:'<path d="m4 17 12-12 3 3L7 20H4zm10-10 3 3"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',logout:'<path d="M9 4H4v16h5m0-8h12m-4-4 4 4-4 4"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',box:'<path d="m12 3 9 5v8l-9 5-9-5V8zm-9 5 9 5 9-5m-9 5v8"/>',activity:'<path d="M3 12h4l3-8 4 16 3-8h4"/>',copy:'<rect x="8" y="8" width="13" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',alert:'<path d="m12 3 10 18H2zM12 9v5m0 3v1"/>'};
const icon=(n,cls='')=>`<svg class="icon ${cls}" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[n]||paths.box}</svg>`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,screen='dashboard',selected=null,tab='overview',search='',taskFilter='all',showArchived=false,saving=false,importing=false,online=true,authQueue=Promise.resolve(),authSerial=0;
const byId=(table,id)=>state?.[table]?.find(r=>r.id===id);
const allOffers=()=>state.offers.filter(o=>!byId('niches',o.niche_id)?.archived);
const userOptions=(id)=>`<option value="">Sem responsável</option>${state.users.filter(u=>u.active).map(u=>`<option value="${esc(u.id)}" ${u.id===id?'selected':''}>${esc(u.name)}</option>`).join('')}`;
const countDone=tasks=>tasks.filter(t=>t.status==='done').length;
const pill=(status)=>`<span class="pill ${esc(status)}"><i></i>${esc(labels[status]||status)}</span>`;
const date=(stamp)=>stamp?new Date(stamp*1000).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Bahia'}):'—';
const due=(v)=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}):'Sem prazo';
const button=(action,text,iconName='plus',extra='',cls='primary')=>`<button class="${cls}" data-action="${action}" ${extra}>${icon(iconName)}${esc(text)}</button>`;
const route=(target,id='')=>`data-screen="${target}" data-id="${esc(id)}"`;
const empty=(title,text,action='')=>`<div class="empty">${icon('folder')}<h3>${esc(title)}</h3><p>${esc(text)}</p>${action}</div>`;
const progress=(tasks)=>`<div class="progress"><span style="width:${tasks.length?100*countDone(tasks)/tasks.length:0}%"></span></div>`;
const link=(url,name)=>url?`<a class="textlink" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${icon('link')}${esc(name)}${icon('arrow')}</a>`:`<span class="missing">${esc(name)} a adicionar</span>`;

async function request(path,body){
 const response=await fetch('api/'+path,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});
 const value=await response.json();if(!response.ok){const e=new Error(value.error||'Não foi possível concluir.');e.status=response.status;throw e;}return value;
}
function toast(message,error=false){const n=document.querySelector('#toast');n.textContent=message;n.className='visible'+(error?' error':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.className='',4500);}
async function command(body){
 if(saving)throw new Error('Aguarde a alteração atual.');saving=true;
 try{const value=await request('command',{command_id:body.command_id||crypto.randomUUID(),...body});state=value.state;online=true;render();return value.result;}
 catch(e){if(e.status===409)await refresh(false);if(e.status===401){state=null;modalRoot.innerHTML='';renderLogin(e.message);}throw e;}
 finally{saving=false;}
}
async function refresh(redraw=true){
 const serial=authSerial;
 try{const fresh=await request('state');if(serial!==authSerial)return;const changed=!state||fresh.revision!==state.revision||fresh.me.id!==state.me.id;if(!state||fresh.me.id!==state.me.id||fresh.revision>=state.revision)state=fresh;online=true;if(redraw&&changed)render();updateConnection();}
 catch(e){if(e.status===401){state=null;modalRoot.innerHTML='';renderLogin(e.message);}else{online=false;updateConnection();}}
}
function updateConnection(){const n=document.querySelector('#connection');if(n){n.className='connection'+(online?'':' offline');n.innerHTML=`<i></i>${online?'Sincronizado':'Sem conexão — tente novamente'}`;}}
async function authenticate(){
 const serial=++authSerial;const token=new URLSearchParams(location.hash.slice(1)).get('acesso');
 if(token)history.replaceState(null,'',location.pathname+location.search);
 authQueue=authQueue.catch(()=>{}).then(async()=>{if(token)await request('access',{token});return request('auth');});
 try{const auth=await authQueue;if(serial!==authSerial)return;if(auth.signed_in){await refresh(false);render();}else renderLogin();}
 catch(e){if(serial===authSerial){state=null;renderLogin(e.message);}}
}
function renderLogin(error=''){
 app.innerHTML=`<div class="login"><header><a class="brand" href="./"><span>${icon('folder')}</span>OfferVault</a><span>Central da operação</span></header><main><div class="login-icon">${icon('folder')}</div><span class="eyebrow">TUDO NO MESMO LUGAR</span><h1>Uma operação.<br>Todos na mesma página.</h1><p>Organize ofertas, idiomas, entregáveis e lançamentos.<br>Entre pelo link pessoal que recebeu da equipe.</p>${error?`<div class="errornotice">${esc(error)}</div>`:''}<div class="login-foot">${icon('users')}Acesso por link, sem senha.</div><details><summary>Sou responsável pelo espaço</summary><p>Use seu acesso de administrador já aberto no Ciclo40 para iniciar a central. Depois você poderá criar e guardar seu link próprio.</p>${button('bootstrap','Entrar com meu acesso do Ciclo40','arrow')}</details></main><footer>OfferVault · Clareza para produzir. Organização para crescer.</footer></div>`;
}
function shell(content,title){
 const nav=[['dashboard','grid','Visão geral'],['niches','folder','Nichos'],['tasks','tasks','Tarefas da equipe'],['shops','shop','Shopifys'],['team','users','Equipe & acessos'],['settings','grid','Configurações']];
 app.innerHTML=`<div class="layout"><aside class="sidebar"><a class="brand" href="./"><span>${icon('folder')}</span>OfferVault<small>OPERAÇÃO</small></a><button class="collapse-sidebar" data-action="collapse-sidebar" aria-label="Recolher ou expandir menu">${icon('chevron')}</button><div class="workspace-label">SEU ESPAÇO DE TRABALHO</div><nav>${nav.map(([s,i,n])=>`<button ${route(s)} class="navitem ${(screen===s||(s==='niches'&&['niche','offer','language','launch'].includes(screen)))?'active':''}">${icon(i)}<span>${n}</span>${s==='tasks'?`<small>${state.tasks.filter(t=>t.status==='blocked').length||''}</small>`:''}</button>`).join('')}</nav><div class="sidebar-note"><span>Da ideia à expansão.</span><p>A próxima etapa fica mais clara quando a equipe trabalha junta.</p><div class="note-folders">${icon('folder')}${icon('globe')}${icon('check')}</div></div><div class="profile"><span class="avatar">${esc(state.me.name.slice(0,2).toUpperCase())}</span><div><strong>${esc(state.me.name)}</strong><small>${state.me.role==='owner'?'Responsável pelos acessos':'Equipe da operação'}</small></div><button data-action="logout" class="iconbtn" title="Sair da conta" aria-label="Sair da conta">${icon('logout')}</button></div></aside><div class="main"><header class="topbar"><span>${esc(title)}</span><label class="global-search">${icon('search')}<input data-global-search placeholder="Pesquisar na operação…" value="${screen==='search'?esc(search):''}" aria-label="Pesquisar na operação"></label><div><span id="connection" class="connection"><i></i>Sincronizado</span>${button('refresh','Atualizar','activity','','plain')}<button class="iconbtn" data-action="toggle-theme" title="Alternar tema" aria-label="Alternar tema">${document.documentElement.dataset.theme==='dark'?'☀':'☾'}</button><button class="iconbtn mobile-logout" data-action="logout" title="Sair" aria-label="Sair da conta">${icon('logout')}</button><span class="mobile-brand">OfferVault</span></div></header><main id="content">${content}</main><footer class="mainfooter"><span>OfferVault</span><span>Alterações compartilhadas com a equipe.</span>${button('export','Exportar dados','download','','plain')}</footer></div></div>`;
 updateConnection();document.title='OfferVault — '+title;
}
function head(eyebrow,title,subtitle,buttons=''){return `<div class="pagehead"><div><span class="eyebrow">${esc(eyebrow)}</span><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div><div class="headbuttons">${buttons}</div></div>`;}
function stats(items){return `<div class="stats">${items.map(([i,value,title,detail])=>`<section><span class="stat-icon">${icon(i)}</span><div><span>${esc(title)}</span><strong>${esc(value)}</strong><small>${esc(detail||'')}</small></div></section>`).join('')}</div>`;}
function breadcrumb(parts){return `<div class="breadcrumb"><button ${route('niches')}>Nichos</button>${parts.map(p=>`${icon('chevron')}<button ${route(p.screen,p.id)}>${esc(p.name)}</button>`).join('')}</div>`;}
function offerContext(offer){const n=byId('niches',offer.niche_id);return breadcrumb([{name:n.name,screen:'niche',id:n.id},{name:offer.name,screen:'offer',id:offer.id}]);}
function taskContext(task){const offer=byId('offers',task.offer_id),niche=byId('niches',offer?.niche_id);let extra='Base em inglês';if(task.scope==='language')extra=byId('languages',task.scope_id)?.name||'Idioma';if(task.scope==='launch'){const launch=byId('launches',task.scope_id);extra=(byId('languages',launch?.language_id)?.name||'Idioma')+' · '+(byId('shops',launch?.shop_id)?.name||'Loja');}return `${niche?.name||''} / ${extra}`;}
function taskRows(tasks,context=false){
 if(!tasks.length)return '<div class="small-empty">Nenhuma tarefa nesta seleção.</div>';
 return `<div class="task-list">${tasks.sort((a,b)=>a.position-b.position||a.created_at-b.created_at).map(t=>`<div class="taskrow ${t.status==='done'?'completed':''}"><button class="checkbtn ${t.status==='done'?'checked':''}" data-action="toggle-task" data-id="${esc(t.id)}" aria-label="${t.status==='done'?'Reabrir':'Concluir'} ${esc(t.title)}">${t.status==='done'?icon('check'):''}</button><div class="taskname"><button data-action="edit-task" data-id="${esc(t.id)}">${esc(t.title)}</button>${context?`<small>${esc(taskContext(t))}</small>`:''}${t.status==='blocked'?`<span class="block-reason">${icon('alert')}${esc(t.blocked_reason)}</span>`:''}${t.result_url?link(t.result_url,'Ver resultado'):''}</div><button class="task-status" data-action="edit-task" data-id="${esc(t.id)}">${pill(t.status)}</button><div class="task-owner">${t.owner_id?`<span class="tiny-avatar">${esc(byId('users',t.owner_id)?.name.slice(0,2).toUpperCase())}</span><span>${esc(byId('users',t.owner_id)?.name)}</span>`:'<span class="unassigned">Sem responsável</span>'}</div><span class="taskdue ${t.due_date&&t.due_date<new Date().toLocaleDateString('en-CA',{timeZone:'America/Bahia'})&&t.status!=='done'?'late':''}">${esc(due(t.due_date))}</span><button data-action="edit-task" data-id="${esc(t.id)}" class="iconbtn" aria-label="Editar ${esc(t.title)}">${icon('edit')}</button></div>`).join('')}</div>`;
}
function nicheCard(n){
 const offers=state.offers.filter(o=>o.niche_id===n.id),langs=state.languages.filter(l=>offers.some(o=>o.id===l.offer_id)),running=langs.filter(l=>l.operational_status==='active'),tasks=state.tasks.filter(t=>offers.some(o=>o.id===t.offer_id)),pending=tasks.filter(t=>t.status!=='done');
 return `<button class="niche-card" ${route('niche',n.id)}><div class="cardtop"><span class="folder-art">${icon('folder')}</span><span class="category">${esc(n.archived?'Arquivado':byId('categories',n.category_id)?.name||n.category||'Nicho')}</span></div><h3>${esc(n.name)}</h3>${pill(n.stage)}<p>${esc(n.notes||'Produtos, idiomas e entregáveis em um só lugar.')}</p><div class="cardnumbers"><span>Ciclo <strong>${n.cycle}</strong></span><span><strong>${langs.length}</strong> versões</span></div><div class="languagechips">${langs.slice(0,6).map(l=>`<span class="langcode ${running.some(x=>x.id===l.id)?'active':''}">${esc(l.code.toUpperCase())}</span>`).join('')}${langs.length>6?`<span>+${langs.length-6}</span>`:''}${!langs.length?'<span class="muted">Idiomas a cadastrar</span>':''}</div><div class="cardbottom"><span>${pending.length} ${pending.length===1?'pendência':'pendências'}${running.length?` · ${running.length} rodando`:''}</span>${icon('arrow')}</div></button>`;
}
function dashboard(){
 const offers=allOffers(),niches=state.niches.filter(n=>!n.archived),running=state.languages.filter(l=>l.operational_status==='active'),pending=state.tasks.filter(t=>t.status!=='done'&&offers.some(o=>o.id===t.offer_id)),blocked=pending.filter(t=>t.status==='blocked'),my=pending.filter(t=>t.owner_id===state.me.id);
 return head('CENTRAL DA OPERAÇÃO','Tudo pronto para avançar?','Veja o que precisa de atenção e continue de onde a equipe parou.',button('new-niche','Novo nicho'))+stats([['folder',niches.length,'Nichos cadastrados',`${offers.filter(o=>o.phase==='production').length} ciclos em produção`],['globe',running.length,'Idiomas ativos','Ativos: atendem às expectativas'],['tasks',pending.length,'Tarefas pendentes',`${my.length} atribuídas a você`],['alert',blocked.length,'Bloqueios',blocked.length?'Precisam de atenção':'Caminho livre para a equipe']])+`<div class="sectionhead"><div><h2>Seus nichos</h2><p>Abra uma pasta para encontrar ofertas, idiomas e materiais.</p></div><button class="textbutton" ${route('niches')}>Ver todos ${icon('arrow')}</button></div><div class="niche-grid">${niches.slice(0,6).map(nicheCard).join('')}${!niches.length?empty('Comece pelo primeiro nicho','Depois, adicione as ofertas e os idiomas que a equipe vai trabalhar.',button('new-niche','Criar nicho')):''}</div><div class="dashboard-bottom"><section class="panel"><div class="panelhead"><div><h2>O que precisa de atenção</h2><p>Bloqueios, revisões e tarefas sem responsável.</p></div><button class="textbutton" ${route('tasks')}>Abrir tarefas ${icon('arrow')}</button></div>${taskRows(pending.filter(t=>t.status==='blocked'||t.status==='review'||!t.owner_id).slice(0,6),true)}</section><section class="panel activity-panel"><div class="panelhead"><h2>Últimas alterações</h2>${icon('activity')}</div>${activities(state.activity.slice(0,7))}</section></div>`;
}
function activities(rows){return rows.length?`<div class="activities">${rows.map(a=>`<div><span class="activity-dot"></span><p><strong>${esc(a.user_name)}</strong><span>${esc(a.summary)}</span><small>${date(a.created_at)}</small></p></div>`).join('')}</div>`:'<div class="small-empty">As alterações da equipe aparecerão aqui.</div>';}
function nichesView(){const list=state.niches.filter(n=>(showArchived||!n.archived)&&`${n.name} ${n.category} ${byId('categories',n.category_id)?.name||''} ${n.notes} ${n.tags} ${n.description}`.toLowerCase().includes(search.toLowerCase()));return head('BIBLIOTECA DA OPERAÇÃO','Nichos','Pastas para organizar cada frente de produção.',button('new-niche','Novo nicho'))+`<div class="toolbar"><label class="search">${icon('search')}<input data-search placeholder="Pesquisar nichos…" value="${esc(search)}"></label><button class="secondary" data-action="toggle-archived">${showArchived?'Ocultar arquivados':'Mostrar arquivados'}</button><span>${list.length} nichos</span></div><div class="niche-grid">${list.map(nicheCard).join('')}${!list.length?empty('Nenhum nicho nesta seleção','Crie uma pasta ou ajuste sua pesquisa.') :''}</div>`;}
function nicheView(){const n=byId('niches',selected);if(!n)return nichesView();const o=state.offers.find(o=>o.niche_id===n.id);return o?offerView(o.id,true):empty('Ciclo a iniciar','Atualize a página para abrir a produção deste nicho.');}
function offerView(offerId=selected,embedded=false){
 const o=byId('offers',offerId);if(!o)return nichesView();const n=byId('niches',o.niche_id);const langs=state.languages.filter(l=>l.offer_id===o.id),tasks=state.tasks.filter(t=>t.scope==='offer'&&t.scope_id===o.id);const tabs=[['overview','Visão geral'],['production','Base em inglês'],['languages','Matriz de idiomas'],['resources','Drive & acessos'],['results','Status & migrações'],['gamma','Contas Gamma'],['history','Ciclos anteriores'],['activity','Atividade']];
 let content='';
 if(tab==='overview'){const remaining=state.tasks.filter(t=>t.offer_id===o.id&&t.status!=='done'),base=langs.find(l=>l.wave==='base');content=stats([['tasks',countDone(tasks)+'/'+tasks.length,'Base em inglês','Produção realizada uma vez'],['globe',langs.filter(l=>l.wave!=='base').length,'Traduções cadastradas','A partir da base inglesa'],['check',langs.filter(l=>l.operational_status==='active').length,'Idiomas ativos','Candidatos a migração'],['alert',remaining.filter(t=>t.status==='blocked').length,'Bloqueios','Com motivo e responsável']])+`<div class="workspace-summary"><section class="panel"><h3>Dados do nicho</h3><p>${esc(n.description||'Descrição a preencher.')}</p><p>Público: ${esc(n.audience||'a definir')}<br>Categoria: ${esc(byId('categories',n.category_id)?.name||'a definir')}<br>Prioridade: ${esc({low:'Baixa',normal:'Normal',high:'Alta',urgent:'Urgente'}[n.priority])}<br>Modelo: ${esc(n.commercial_model)}<br>Tags: ${esc(n.tags||'a definir')}<br>Criado em: ${date(n.created_at)}</p></section><section class="panel"><h3>Base inglesa → traduções → lojas</h3><p>Primeiro produza a base inglesa. Depois traduza integralmente e publique cada versão nas Shopifys escolhidas. Marque os idiomas que estão ativos antes de migrar.</p><button class="textbutton" data-tab="production">Abrir produção ${icon('arrow')}</button><button class="textbutton" data-tab="languages">Abrir matriz de idiomas ${icon('arrow')}</button></section><section class="panel"><h3>Links, materiais & contas</h3><p>As pastas Drive e o acesso Gamma deste ciclo ficam neste nicho.</p><button class="textbutton" data-tab="resources">Arquivos e acessos ${icon('arrow')}</button><button class="textbutton" data-tab="gamma">Contas Gamma ${icon('arrow')}</button></section></div><section class="panel"><div class="panelhead"><h2>Próximas tarefas deste nicho</h2></div>${taskRows(remaining.slice(0,5))}</section>`;}
 if(tab==='production')content=`<section class="panel"><div class="panelhead"><div><h2>Produção única em inglês</h2><p>Oferta, nomes, capas, imagens, copy, página e books. Esta base será traduzida integralmente para os demais idiomas.</p></div><span class="muted">${countDone(tasks)} de ${tasks.length} concluídas</span>${button('new-task','Adicionar tarefa','plus',`data-scope="offer" data-id="${esc(o.id)}"`,'secondary')}</div>${taskRows(tasks)}</section><div class="flow-note">${icon('arrow')}Depois da base inglesa, traduza para os demais idiomas e vincule as Shopifys onde eles serão lançados.</div>`;
 if(tab==='languages')content=`<div class="sectionhead"><div><h2>Matriz de idiomas de ${esc(n.name)}</h2><p>Marque as Shopifys e o Facebook. Ativo indica que está atendendo às expectativas.</p></div>${button('new-language','Adicionar idioma','plus',`data-id="${esc(o.id)}"`)}</div><section class="panel matrix-panel"><table class="matrix niche-matrix simple-matrix"><thead><tr><th>Idioma</th><th>Situação</th>${state.shops.filter(s=>s.active).map(s=>`<th>Shopify ${state.shops.indexOf(s)+1}<small>${esc(s.name)}</small></th>`).join('')}<th>Facebook</th><th></th></tr></thead><tbody>${langs.map(l=>`<tr><th>${esc(l.name)}<small>${esc(l.code.toUpperCase())}${l.wave==='base'?' · BASE':''}</small></th><td><button data-action="set-language-status" data-id="${esc(l.id)}" class="plain">${performancePill(l)}</button></td>${state.shops.filter(s=>s.active).map(s=>`<td><input class="matrix-checkbox" type="checkbox" aria-label="${esc(l.name)} na ${esc(s.name)}" data-language-shop="${esc(l.id)}" data-shop="${esc(s.id)}" ${state.launches.some(x=>x.language_id===l.id&&x.shop_id===s.id)?'checked':''}></td>`).join('')}<td><input class="matrix-checkbox" type="checkbox" aria-label="Facebook de ${esc(l.name)}" data-language-facebook="${esc(l.id)}" ${l.facebook?'checked':''}></td><td>${button('edit-language','Configurar','edit',`data-id="${esc(l.id)}"`,'plain')}<button class="textbutton" ${route('language',l.id)}>Tarefas ${icon('arrow')}</button></td></tr>`).join('')}</tbody></table></section>`;

 if(tab==='resources'){const base=langs.find(l=>l.wave==='base');content=base?resourcesSection(base,'Arquivos do nicho & área de membros'):'';}

 if(tab==='results')content=statusSection(langs);
 if(tab==='gamma')content=nicheGamma(n,o);
 if(tab==='history')content=historySection(n);
 if(tab==='activity'){const entities=new Set([o.id,...langs.map(l=>l.id),...state.launches.filter(l=>langs.some(x=>x.id===l.language_id)).map(l=>l.id),...state.tasks.filter(t=>t.offer_id===o.id).map(t=>t.id),...state.deliverables.filter(d=>d.offer_id===o.id).map(d=>d.id)]);content=`<section class="panel"><div class="panelhead"><h2>Atividade deste nicho</h2></div>${activities(state.activity.filter(a=>entities.has(a.entity_id)))}</section>`;}
 return breadcrumb([{name:n.name,screen:'niche',id:n.id}])+head('NICHO · CICLO '+n.cycle,n.name,n.notes||'Da base inglesa à tradução, validação e expansão.',pill(n.stage)+button('edit-niche','Editar nicho','edit',`data-id="${esc(n.id)}"`,'secondary')+button('restart-niche','Novo desenvolvimento','activity',`data-id="${esc(n.id)}"`,'secondary'))+`<div class="offer-summary"><span>${icon('users')}${esc(byId('users',n.owner_id||o.owner_id)?.name||'Responsável a definir')}</span><span>${icon('globe')}${langs.length} idiomas cadastrados</span><span>${icon('check')}Situação por idioma</span></div>${state.trello_sources?.some(x=>x.niche_id===n.id)?`<div class="offer-summary">${state.trello_sources.filter(x=>x.niche_id===n.id).map(x=>link(x.card_url,"Cartão Trello · "+x.source_name)).join('')}</div>`:''}<div class="tabs">${tabs.map(([t,n])=>`<button data-tab="${t}" class="${tab===t?'active':''}">${esc(n)}</button>`).join('')}</div>${content}`;
}
function languageStatus(l){const launches=state.launches.filter(x=>x.language_id===l.id);return launches.some(x=>x.status==='running')?'running':launches.some(x=>x.status==='testing')?'testing':launches.length&&launches.every(x=>x.status==='paused')?'paused':launches.some(x=>x.status==='ready')?'ready':'preparing';}
function languageCard(l){const tasks=state.tasks.filter(t=>t.scope==='language'&&t.scope_id===l.id),launches=state.launches.filter(x=>x.language_id===l.id);return `<button class="language-card" ${route('language',l.id)}><div class="cardtop"><span class="language-symbol">${esc(l.code.toUpperCase())}</span>${pill(languageStatus(l))}</div><h3>${esc(l.name)}</h3>${performancePill(l)}<p>${l.wave==='base'?'Base original em inglês':l.wave==='pilot'?'Tradução':'Tradução adicional'}</p><div class="shop-chips">${launches.map(x=>`<span class="${x.status==='running'?'live':''}">${esc(byId('shops',x.shop_id)?.name)}</span>`).join('')}${!launches.length?'<span>Shopify a vincular</span>':''}</div>${progress(tasks)}<div class="cardbottom"><span>${l.wave==='base'?'Produção original':countDone(tasks)+'/'+tasks.length+' etapas de tradução'}</span>${icon('arrow')}</div></button>`;}
function languageView(){
 const l=byId('languages',selected);if(!l)return nichesView();const o=byId('offers',l.offer_id),n=byId('niches',o.niche_id),tasks=state.tasks.filter(t=>l.wave==='base'?t.scope==='offer'&&t.scope_id===o.id:t.scope==='language'&&t.scope_id===l.id),launches=state.launches.filter(x=>x.language_id===l.id);
 return breadcrumb([{name:n.name,screen:'niche',id:n.id},{name:o.name,screen:'offer',id:o.id},{name:l.name,screen:'language',id:l.id}])+head(l.code.toUpperCase()+' · '+(l.wave==='base'?'BASE ORIGINAL':l.wave==='pilot'?'TRADUÇÃO DE TESTE':'TRADUÇÃO DE EXPANSÃO'),l.name,`${n.name} · Materiais desta versão e lançamentos por Shopify.`,button('edit-language','Editar idioma','edit',`data-id="${esc(l.id)}"`,'secondary')+button('clone-language','Novo idioma a partir deste','copy',`data-id="${esc(l.id)}"`,'secondary'))+`<section class="panel"><div class="panelhead"><div><h2>Lançamentos nas Shopifys</h2><p>A mesma versão pode operar em mais de uma loja simultaneamente.</p></div>${button('new-launch','Vincular Shopify','plus',`data-id="${esc(l.id)}"`)}</div><div class="launch-grid">${launches.map(x=>`<button class="launch-card" ${route('launch',x.id)}><div class="cardtop">${icon('shop')}${pill(x.status)}</div><h3>${esc(byId('shops',x.shop_id)?.name)}</h3><p>${esc(x.campaign_name||'Campanha a definir')}</p><div class="cardbottom"><span>Produto · Página · Campanha</span>${icon('arrow')}</div></button>`).join('')}${!launches.length?'<div class="small-empty">Vincule uma Shopify para cadastrar produto, página e campanha.</div>':''}</div></section><section class="panel"><div class="panelhead"><div><h2>${l.wave==='base'?'Produção única em inglês':'Tradução integral da base inglesa'}</h2><p>${l.wave==='base'?'A base é produzida uma vez por ciclo.':'Traduza os materiais existentes e revise o resultado.'}</p></div>${button('new-task','Adicionar tarefa','plus',`data-scope="${l.wave==='base'?'offer':'language'}" data-id="${esc(l.wave==='base'?o.id:l.id)}"`,'secondary')}</div>${taskRows(tasks)}</section>${statusSection([l])}`;
}
function launchView(){
 const x=byId('launches',selected);if(!x)return nichesView();const l=byId('languages',x.language_id),o=byId('offers',l.offer_id),n=byId('niches',o.niche_id),shop=byId('shops',x.shop_id),tasks=state.tasks.filter(t=>t.scope==='launch'&&t.scope_id===x.id);
 return breadcrumb([{name:n.name,screen:'niche',id:n.id},{name:o.name,screen:'offer',id:o.id},{name:l.name,screen:'language',id:l.id}])+head('LANÇAMENTO POR LOJA',shop.name,`${n.name} / ${l.name}`,pill(x.status)+button('edit-launch','Editar lançamento','edit',`data-id="${esc(x.id)}"`))+`<div class="resource-grid launch-resources"><section class="panel"><span class="resource-icon">${icon('shop')}</span><h3>Produto & checkout</h3>${link(x.product_url,'Produto na Shopify')}${link(x.checkout_url,'Link do checkout')}<p class="smallmeta">Produto: ${esc(x.product_id||'a informar')} · Variante: ${esc(x.variant_id||'a informar')}</p></section><section class="panel"><span class="resource-icon">${icon('file')}</span><h3>Página de vendas</h3>${link(x.page_url,'Página na Shopify')}${link(l.member_url,'Área de membros')}</section><section class="panel"><span class="resource-icon">${icon('activity')}</span><h3>Campanha no Facebook</h3><p>${esc(x.campaign_name||'Nome a informar')}</p>${link(x.campaign_url,'Abrir campanha')}</section></div><section class="panel"><div class="panelhead"><div><h2>Publicação nesta Shopify</h2><p>Produto e página na loja, conferência e campanha.</p></div>${button('new-task','Adicionar tarefa','plus',`data-scope="launch" data-id="${esc(x.id)}"`,'secondary')}</div>${taskRows(tasks)}</section>${x.notes?`<section class="panel"><div class="panelhead"><h2>Observações do lançamento</h2></div><p class="panelbody notes">${esc(x.notes)}</p></section>`:''}`;
}
function resourcesSection(l,title){return `<section class="panel"><div class="panelhead"><div><h2>${esc(title)}</h2><p>Arquivos organizados no Drive. Guarde aqui os links das pastas e do acesso.</p></div>${button('edit-resources','Editar links','edit',`data-id="${esc(l.id)}"`,'secondary')}</div><div class="resource-grid drive-resources">${[['Entregáveis',l.deliverables_url],['Criativos',l.creatives_url],['Imagens do site',l.site_images_url],['Área de membros',l.member_url]].map(([name,url])=>`<article class="doc-card"><span class="resource-icon">${icon('folder')}</span><h3>${esc(name)}</h3>${link(url,'Abrir '+name.toLowerCase())}</article>`).join('')}</div></section>`;}
function performanceLabel(l){return {active:'Ativo',inactive:'Desativado',preparing:'Em preparação'}[l.operational_status||'preparing'];}
function performancePill(l){return `<span class="pill performance ${l.operational_status==='active'?'good':l.operational_status==='inactive'?'bad':'unmeasured'}">${esc(performanceLabel(l))}</span>`;}
function nicheGamma(n,o){const meta=state.gamma_access.find(g=>g.niche_id===n.id&&g.cycle===n.cycle);return `<section class="panel"><div class="panelhead"><div><h2>Acesso Gamma de ${esc(n.name)}</h2><p>Um campo de texto para o login e a senha usados neste nicho.</p></div>${button('edit-credentials','Abrir / editar acesso','edit',`data-id="${esc(n.id)}"`)}</div><div class="panelbody"><p class="notes">${meta?.has_text?'Login e senha cadastrados.':'Nenhum acesso cadastrado neste ciclo.'}</p>${meta?.has_text?`<p class="smallmeta">Atualizado por ${esc(byId('users',meta.updated_by)?.name)} · ${date(meta.updated_at)}</p>`:''}</div></section>`;}
function statusSection(langs){return `<section class="panel"><div class="panelhead"><div><h2>Situação dos idiomas</h2><p>Ativo: está atendendo às expectativas. Desativado: não atendeu. Migre apenas os ativos.</p></div></div><div class="result-list">${langs.map(l=>`<article class="result-row"><div><strong>${esc(l.name)} · ${esc(l.code.toUpperCase())}</strong>${performancePill(l)}<p>${esc(l.notes||'Sem observações.')}</p></div>${button('set-language-status','Alterar situação','edit',`data-id="${esc(l.id)}"`,'secondary')}${button('migrate-language','Planejar migração','arrow',`data-id="${esc(l.id)}"`,'secondary')}</article>`).join('')}</div></section><section class="panel"><div class="panelhead"><h2>Migrações deste ciclo</h2></div><div class="result-list">${state.migrations.filter(m=>langs.some(l=>l.id===m.language_id)).map(m=>{const task=byId('tasks',m.task_id),l=byId('languages',m.language_id);return `<article class="result-row"><div><strong>${esc(l.name)} · ${esc(byId('shops',m.from_shop_id)?.name)} → ${esc(byId('shops',m.to_shop_id)?.name)}</strong><p>${esc(byId('users',task?.owner_id)?.name||'Responsável a definir')}</p>${pill(task?.status||'todo')}</div>${button('edit-task','Editar tarefa','edit',`data-id="${esc(m.task_id)}"`,'secondary')}<button class="secondary" ${route('launch',m.launch_id)}>Abrir destino ${icon('arrow')}</button></article>`;}).join('')||'<div class="small-empty">Planeje migrações a partir dos idiomas ativos.</div>'}</div></section>`;}
function historySection(n){return `<section class="panel"><div class="panelhead"><div><h2>Ciclos anteriores de ${esc(n.name)}</h2><p>O novo desenvolvimento começa zerado. A operação anterior permanece arquivada.</p></div></div><div class="result-list">${state.niche_cycles.filter(c=>c.niche_id===n.id).sort((a,b)=>b.cycle-a.cycle).map(c=>`<article class="result-row"><div><strong>Ciclo ${c.cycle}</strong><p>${esc(c.notes)}</p><small>${date(c.created_at)} · ${esc(byId('users',c.restarted_by)?.name)}</small></div>${button('edit-credentials','Acesso Gamma do ciclo','link',`data-id="${esc(c.niche_id)}" data-cycle="${c.cycle}"`,'secondary')}${button('show-cycle','Ver histórico','folder',`data-id="${esc(c.id)}"`,'secondary')}${button('export-cycle','Exportar ciclo','download',`data-id="${esc(c.id)}"`,'secondary')}</article>`).join('')||'<div class="small-empty">Este é o primeiro ciclo do nicho.</div>'}</div></section>`;}
function tasksView(){
 const offers=allOffers(),list=state.tasks.filter(t=>offers.some(o=>o.id===t.offer_id)&&`${t.title} ${taskContext(t)} ${byId('users',t.owner_id)?.name||''}`.toLowerCase().includes(search.toLowerCase())&&(taskFilter==='all'||taskFilter==='mine'&&t.owner_id===state.me.id||taskFilter==='unassigned'&&!t.owner_id||t.status===taskFilter));
 return head('TRABALHO COMPARTILHADO','Tarefas da equipe','Quem faz o quê, o que está pronto e o que impede a próxima etapa.')+`<div class="toolbar"><label class="search">${icon('search')}<input data-search placeholder="Pesquisar tarefa, produto ou pessoa…" value="${esc(search)}"></label><select id="task-filter" aria-label="Filtrar tarefas">${[['all','Todas as tarefas'],['mine','Minhas tarefas'],['unassigned','Sem responsável'],['todo','Pendentes'],['doing','Em andamento'],['blocked','Bloqueadas'],['review','Em revisão'],['done','Concluídas']].map(([v,n])=>`<option value="${v}" ${v===taskFilter?'selected':''}>${n}</option>`).join('')}</select><span>${list.length} tarefas</span></div><section class="panel">${taskRows(list,true)}</section>`;
}
function shopsView(){return head('LOJAS DA OPERAÇÃO','Shopifys','Lojas reutilizadas em vários produtos e idiomas.',button('new-shop','Adicionar Shopify'))+`<div class="resource-grid">${state.shops.map(s=>`<article class="shop-card"><div class="cardtop"><span class="resource-icon">${icon('shop')}</span><span class="pill ${s.active?'running':'paused'}">${s.active?'Ativa':'Pausada'}</span><button class="iconbtn" data-action="edit-shop" data-id="${esc(s.id)}" aria-label="Editar ${esc(s.name)}">${icon('edit')}</button></div><h3>${esc(s.name)}</h3><p>${state.launches.filter(x=>x.shop_id===s.id).length} lançamentos vinculados</p>${link(s.domain,'Abrir loja')}${s.notes?`<p class="notes">${esc(s.notes)}</p>`:''}</article>`).join('')}</div>`;}
function teamView(){return head('PESSOAS & HISTÓRICO','Equipe & acessos','Toda a equipe pode editar a operação. Os links identificam cada pessoa.',state.me.role==='owner'?button('new-user','Adicionar pessoa'):'' )+`<section class="panel"><div class="panelhead"><h2>Pessoas do espaço</h2><span class="muted">${state.users.filter(u=>u.active).length} acessos ativos</span></div><div class="team-list">${state.users.map(u=>`<div class="teamrow"><span class="avatar">${esc(u.name.slice(0,2).toUpperCase())}</span><div><strong>${esc(u.name)}</strong><small>${esc(u.email||'Acesso por link pessoal')}${u.role==='owner'?' · Responsável pelos acessos':''}</small></div><span class="pill ${u.active?'running':'paused'}">${u.active?'Ativo':'Desativado'}</span>${state.me.role==='owner'?`${button('rotate-user','Gerar link','link',`data-id="${esc(u.id)}"`,'secondary')}${u.role!=='owner'&&u.active?button('disable-user','Desativar','close',`data-id="${esc(u.id)}"`,'plain'):''}`:''}</div>`).join('')}</div></section><div class="flow-note">${icon('link')}Guarde seu link pessoal. Um novo link substitui o anterior e encerra as sessões antigas daquela pessoa.</div>`;}
function settingsView(){return head('PREFERÊNCIAS & CADASTROS','Configurações','Categorias, aparência, lojas e acessos do espaço.')+`${state.me.role==='owner'?`<section class="panel"><div class="panelhead"><div><h2>Importar do Trello</h2><p>Cadastre nichos e idiomas a partir de um arquivo revisado. Os links de origem ficam no nicho.</p></div>${button('import-trello','Importar arquivo','download')}</div></section>`:''}<section class="panel"><div class="panelhead"><h2>Aparência</h2>${button('toggle-theme','Alternar tema claro / escuro','grid','','secondary')}${button('collapse-sidebar','Recolher / expandir menu','chevron','','secondary')}</div></section><section class="panel"><div class="panelhead"><div><h2>Categorias dos nichos</h2><p>Cadastros reutilizados nas pastas.</p></div>${button('new-category','Adicionar categoria')}</div><div class="result-list">${state.categories.map(c=>`<article class="result-row"><strong>${esc(c.name)}</strong>${button('edit-category','Editar','edit',`data-id="${esc(c.id)}"`,'secondary')}</article>`).join('')}</div></section><section class="panel"><div class="panelhead"><h2>Lojas & equipe</h2><button class="secondary" ${route('shops')}>Gerenciar Shopifys</button><button class="secondary" ${route('team')}>Gerenciar equipe e links</button></div></section>`;}
function searchView(){const q=search.toLowerCase(),hits=[];if(q.length>=2){const match=r=>Object.values(r).some(v=>typeof v==='string'&&v.toLowerCase().includes(q));for(const n of state.niches.filter(match))hits.push(['Nicho',n.name,'niche',n.id]);for(const l of state.languages.filter(match))hits.push(['Idioma',byId('niches',byId('offers',l.offer_id)?.niche_id)?.name+' · '+l.name,'language',l.id]);for(const t of state.tasks.filter(match))hits.push(['Tarefa',t.title+' · '+taskContext(t),'offer',t.offer_id]);for(const x of state.launches.filter(match))hits.push(['Produto / página / campanha',byId('shops',x.shop_id)?.name+' · '+byId('languages',x.language_id)?.name,'launch',x.id]);for(const s of state.shops.filter(match))hits.push(['Shopify',s.name,'shops','']);}return head('BUSCA NA OPERAÇÃO','Pesquisa global','Encontre nichos, idiomas, Shopifys, tarefas e links cadastrados.')+`<section class="panel"><div class="result-list">${hits.map(([kind,title,target,id])=>`<article class="result-row"><div><small>${esc(kind)}</small><strong>${esc(title)}</strong></div><button class="secondary" ${route(target,id)}>Abrir ${icon('arrow')}</button></article>`).join('')||`<div class="empty"><h3>${q.length<2?'Digite pelo menos dois caracteres':'Nenhum item encontrado'}</h3></div>`}</div></section>`;}
function render(){
 if(!state)return renderLogin();const previous=window.scrollY;
 const views={settings:settingsView,search:searchView,dashboard,niches:nichesView,niche:nicheView,offer:offerView,language:languageView,launch:launchView,tasks:tasksView,shops:shopsView,team:teamView};const titles={settings:'Configurações',search:'Pesquisa global',dashboard:'Visão geral',niches:'Nichos',niche:'Nicho',offer:'Oferta',language:'Idioma',launch:'Lançamento',tasks:'Tarefas da equipe',matrix:'Matriz de idiomas',gamma:'Contas Gamma',shops:'Shopifys',team:'Equipe & acessos'};
 shell((views[screen]||dashboard)(),titles[screen]);window.scrollTo(0,previous);
}
function navigate(s,id){screen=s;selected=id;search='';if(['offer','niche'].includes(s))tab='overview';render();window.scrollTo(0,0);}

function input(name,title,value='',type='text',extra=''){return `<label>${esc(title)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function area(name,title,value=''){return `<label class="wide">${esc(title)}<textarea name="${name}" rows="3">${esc(value)}</textarea></label>`;}
function select(name,title,options,value='',extra=''){return `<label>${esc(title)}<select name="${name}" aria-label="${esc(title)}" ${extra}>${options.map(([v,n])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(n)}</option>`).join('')}</select></label>`;}
function ownerField(value){return `<label>Responsável<select name="owner_id" aria-label="Responsável">${userOptions(value)}</select></label>`;}
function dialog(title,subtitle,fields,onSave,label='Salvar',extra=''){
 modalRoot.innerHTML=`<div class="modal-overlay"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header><div><h2 id="modal-title">${esc(title)}</h2><p>${esc(subtitle)}</p></div><button data-action="close-modal" type="button" class="iconbtn" aria-label="Fechar">${icon('close')}</button></header><form id="editor"><div class="formgrid">${fields}</div>${extra}<p class="form-error" role="alert"></p><footer><button type="button" class="secondary" data-action="close-modal">Cancelar</button><button type="submit" class="primary">${esc(label)} ${icon('arrow')}</button></footer></form></section></div>`;
 const form=modalRoot.querySelector('form');const first=form.querySelector('input,select,textarea');first?.focus();form.commandId=crypto.randomUUID();
 form.addEventListener('submit',async e=>{e.preventDefault();const btn=form.querySelector('[type=submit]');btn.disabled=true;form.querySelector('.form-error').textContent='';try{const values=Object.fromEntries(new FormData(form));await onSave(values,form.commandId,form);if(modalRoot.contains(form))modalRoot.innerHTML='';}catch(err){form.querySelector('.form-error').textContent=err.message;btn.disabled=false;if(err.status===409){form.commandId=crypto.randomUUID();}}});
}
function cleanForm(v){const values={...v};if('owner_id' in values)values.owner_id=values.owner_id||null;if('category_id' in values)values.category_id=values.category_id||null;if('gamma_id' in values)values.gamma_id=values.gamma_id||null;if('pilot_target' in values)values.pilot_target=Number(values.pilot_target);if('active'in values)values.active=Number(values.active);if('archived'in values)values.archived=Number(values.archived);return values;}
function entityForm(entity,row,fields,links={}){
 dialog(row?'Editar cadastro':'Novo cadastro','As alterações ficam disponíveis para toda a equipe.',fields,async(v,command_id)=>{await command(row?{action:'update',entity,id:row.id,version:row.version,values:cleanForm(v),command_id}:{action:'create',entity,values:cleanForm(v),...links,command_id});toast('Cadastro salvo.');});
}
function nicheForm(id){const r=byId('niches',id);entityForm('niches',r,input('name','Nome do nicho',r?.name,'text','required maxlength="250"')+select('category_id','Categoria',[['','Sem categoria'],...state.categories.map(c=>[c.id,c.name])],r?.category_id||'')+ownerField(r?.owner_id)+select('priority','Prioridade',[['low','Baixa'],['normal','Normal'],['high','Alta'],['urgent','Urgente']],r?.priority||'normal')+select('stage','Status do nicho',['idea','research','approved','production','ready','testing','active','expansion','paused','archived'].map(v=>[v,labels[v]]),r?.stage||'idea')+input('tags','Tags (separadas por vírgula)',r?.tags)+input('audience','Público-alvo',r?.audience)+input('commercial_model','Modelo comercial',r?.commercial_model||'Compra única · produto digital')+input('cover_url','Link da imagem de capa',r?.cover_url,'url')+area('description','Descrição do nicho',r?.description)+area('notes','Observações e links de referência',r?.notes));}
function languageForm(id,offerId){const r=byId('languages',id),shops=state.shops.filter(s=>s.active),chosen=state.launches.filter(x=>x.language_id===id).map(x=>x.shop_id);const fields=(r?`<p class="wide"><strong>${esc(r.name)}</strong> · ${esc(r.code.toUpperCase())}</p>`:input('name','Idioma','','text','required list="language-names"')+`<datalist id="language-names">${langCatalog.filter(([c])=>c!=='en').map(([c,n])=>`<option value="${n}">${c}</option>`).join('')}</datalist>`+input('code','Código','','text','required placeholder="Ex.: de"'))+`<fieldset class="wide shop-checks"><legend>Shopifys</legend>${shops.map(s=>`<label><input type="checkbox" name="shops" value="${esc(s.id)}" ${chosen.includes(s.id)?'checked':''}>Shopify ${state.shops.indexOf(s)+1} · ${esc(s.name)}</label>`).join('')}</fieldset><label class="wide checkbox-field"><input type="checkbox" name="facebook" value="1" ${r?.facebook?'checked':''}>Facebook</label>`+select('operational_status','Situação',[['preparing','Em preparação'],['active','Ativo'],['inactive','Desativado']],r?.operational_status||'preparing');dialog(r?'Configurar '+r.name:'Adicionar idioma','Marque as lojas e o Facebook usados por esta versão.',fields,async(v,command_id,form)=>{const values={operational_status:v.operational_status,facebook:form.facebook.checked?1:0};if(!r)values.name=v.name;const result=await command({action:'configure_language',...(r?{id:r.id,version:r.version}:{offer_id:offerId,code:v.code}),values,shop_ids:[...form.querySelectorAll('[name=shops]:checked')].map(e=>e.value),command_id});toast('Idioma configurado.');});if(!r)modalRoot.querySelector('[name=name]').addEventListener('input',e=>{const found=langCatalog.find(([c,n])=>c!=='en'&&n===e.target.value);if(found)modalRoot.querySelector('[name=code]').value=found[0];});}
function resourcesForm(id){const l=byId('languages',id);dialog('Drive & área de membros','Links das pastas deste nicho. Os arquivos permanecem no Drive.',input('deliverables_url','Drive dos entregáveis',l.deliverables_url,'url')+input('creatives_url','Drive dos criativos',l.creatives_url,'url')+input('site_images_url','Drive das imagens do site',l.site_images_url,'url')+input('member_url','Link / Drive da área de membros',l.member_url,'url'),async(v,command_id)=>{await command({action:'update',entity:'languages',id:l.id,version:l.version,values:v,command_id});toast('Links do nicho atualizados.');});}
function launchForm(id,languageId){const r=byId('launches',id);const l=byId('languages',r?.language_id||languageId);if(!r){const options=state.shops.filter(s=>s.active&&!state.launches.some(x=>x.language_id===l.id&&x.shop_id===s.id)).map(s=>[s.id,s.name]);if(!options.length)return toast('Adicione outra Shopify ou abra um lançamento já vinculado.',true);dialog('Vincular Shopify',`Nova publicação de ${l.name}, com checklist independente.`,select('shop_id','Shopify',options)+ownerField(null),async(v,command_id)=>{const result=await command({action:'create',entity:'launches',language_id:l.id,shop_id:v.shop_id,values:{owner_id:v.owner_id||null},command_id});navigate('launch',result.id);toast('Shopify vinculada.');});return;}entityForm('launches',r,select('status','Status do lançamento',LAUNCH_OPTIONS,r.status)+ownerField(r.owner_id)+input('product_url','Link do produto na Shopify',r.product_url,'url')+input('page_url','Link da página de vendas na Shopify',r.page_url,'url')+input('checkout_url','Link do checkout',r.checkout_url,'url')+input('campaign_url','Link da campanha no Facebook',r.campaign_url,'url')+input('campaign_name','Nome da campanha',r.campaign_name)+input('product_id','ID do produto Shopify',r.product_id)+input('variant_id','ID da variante de compra',r.variant_id)+area('notes','Observações desta loja',r.notes));}
const LAUNCH_OPTIONS=['preparing','ready','testing','running','paused'].map(v=>[v,labels[v]]);
function taskForm(id,scope,scopeId){const r=byId('tasks',id);entityForm('tasks',r,input('title','Tarefa',r?.title,'text','required')+select('status','Status',['todo','doing','blocked','review','done'].map(v=>[v,labels[v]]),r?.status||'todo')+ownerField(r?.owner_id)+input('due_date','Prazo',r?.due_date,'date')+area('blocked_reason','O que está bloqueando?',r?.blocked_reason)+input('result_url','Link do resultado ou material pronto',r?.result_url,'url')+area('notes','Observações',r?.notes),{scope,scope_id:scopeId});}
function currentNiche(){if(screen==='niche')return selected;const o=screen==='offer'?byId('offers',selected):screen==='language'?byId('offers',byId('languages',selected)?.offer_id):screen==='launch'?byId('offers',byId('languages',byId('launches',selected)?.language_id)?.offer_id):null;return o?.niche_id;}
function shopForm(id){const r=byId('shops',id);entityForm('shops',r,input('name','Nome da Shopify',r?.name,'text','required')+input('domain','Endereço da loja',r?.domain,'url','placeholder="https://sualoja.com"')+select('active','Disponibilidade',[[1,'Ativa'],[0,'Pausada']],r?.active??1)+area('notes','Observações',r?.notes));}
function showAccess(result){if(result.needs_new_link)return toast('A pessoa já foi cadastrada. Clique em Gerar link para obter um novo acesso.',true);if(!result.access_token)return;const url=new URL(location.pathname,location.origin);url.hash='acesso='+result.access_token;dialog('Link pessoal de acesso',result.name+' · Compartilhe somente com essa pessoa.',input('access_link','Link pessoal',url.href,'text','readonly')+`<p class="smallhint wide">Este link abre o app sem senha. Guarde-o. Os links anteriores dessa pessoa foram substituídos.</p>`,async()=>{await navigator.clipboard.writeText(url.href);toast('Link copiado.');},'Copiar link');}
function trelloImportForm(){
 let importedFile=null;
 const fields=input('import_file','Arquivo de importação','','file','accept=".json,application/json" required')+select('shop_id','Shopify de destino',state.shops.filter(x=>x.active).map(x=>[x.id,x.name]),state.shops.find(x=>x.name==='New Library')?.id)+select('mode','Significado dos itens concluídos',[
 ['shop_only','Publicado na Shopify; Facebook e resultado a confirmar'],
 ['shop_facebook','Publicado na Shopify e no Facebook; resultado a confirmar'],
 ['active','Publicado, no Facebook e atendendo às expectativas']
 ],'shop_only')+`<p class="wide smallhint" id="import-preview">Selecione o arquivo. Itens desmarcados ficam em preparação, sem vincular a loja. Dados existentes e ciclos reiniciados são preservados.</p><p class="wide" id="import-progress" role="status"></p>`;
 dialog('Importar nichos do Trello','Cada nicho recebe sua matriz de idiomas e os cartões de origem.',fields,async(v,command_id,form)=>{
  if(!importedFile)throw new Error('Selecione um arquivo válido.');
  importing=true;const results=[];
  try{
   for(let index=0;index<importedFile.niches.length;index++){
    const payload=importedFile.niches[index];form.querySelector('#import-progress').textContent=`Importando ${index+1} de ${importedFile.niches.length}: ${payload.name}`;
    const result=await command({action:'import_trello',payload,shop_id:v.shop_id,mode:v.mode,command_id:command_id+'-'+index});results.push(result);
   }
   toast(`Importação concluída: ${results.filter(r=>!r.skipped).length} nichos cadastrados ou integrados; ${results.filter(r=>r.skipped).length} já importados.`);
  }catch(e){throw new Error(`${results.length} de ${importedFile.niches.length} nichos processados. ${e.message} Você pode reenviar o mesmo arquivo para continuar.`);}
  finally{importing=false;}
 },'Importar nichos');
 const form=modalRoot.querySelector('form');
 form.querySelector('[name=import_file]').addEventListener('change',async e=>{
  importedFile=null;const preview=form.querySelector('#import-preview');
  try{
   const file=e.target.files[0];if(!file||file.size>2000000)throw new Error('Selecione um arquivo JSON de até 2 MB.');
   const data=JSON.parse(await file.text());if(data.format!=='offervault-trello-v1'||!Array.isArray(data.niches)||!data.niches.length||data.niches.length>150)throw new Error('Formato de importação inválido.');
   if(data.niches.some(n=>!n.name||!Array.isArray(n.languages)||!Array.isArray(n.cards)))throw new Error('Nicho ou checklist incompleto.');
   importedFile=data;const languageCount=data.niches.reduce((sum,n)=>sum+n.languages.length,0),published=data.niches.reduce((sum,n)=>sum+n.languages.filter(l=>l.complete).length,0);
   preview.textContent=`${data.niches.length} nichos · ${languageCount} idiomas do checklist · ${published} publicações marcadas. Itens pendentes não serão tratados como resultado negativo.`;
  }catch(err){preview.textContent=err.message;}
 });
}

async function act(action,data){
 if(importing)return toast('Aguarde a importação terminar.');
 switch(action){
 case 'import-trello':trelloImportForm();break;
 case 'bootstrap':{await request('bootstrap',{});await refresh(false);render();toast('Espaço aberto. Cadastre a equipe e guarde seu link em Equipe & acessos.');break;}
 case 'toggle-theme':{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('offervault-theme',theme);}catch{}render();break;}
 case 'collapse-sidebar':{const value=document.documentElement.dataset.sidebar==='collapsed'?'expanded':'collapsed';document.documentElement.dataset.sidebar=value;try{localStorage.setItem('offervault-sidebar',value);}catch{}break;}
 case 'new-category':case 'edit-category':{const r=byId('categories',data.id);entityForm('categories',r,input('name','Nome da categoria',r?.name,'text','required')+input('color','Cor',r?.color||'#91dfba','color'));break;}
 case 'edit-credentials':{const n=byId('niches',data.id),value=await request('credentials?niche_id='+encodeURIComponent(n.id)+(data.cycle?'&cycle='+encodeURIComponent(data.cycle):''));dialog('Gamma · '+n.name+' · ciclo '+value.cycle,'Login e senha do Gamma usados por este nicho.',area('text','Login e senha',value.text).replace('<textarea','<textarea autocomplete="off" autocapitalize="off" spellcheck="false"'),async(v,command_id)=>{if(value.cycle!==n.cycle)return;await command({action:'save_credentials',niche_id:n.id,cycle:value.cycle,version:value.version,text:v.text,command_id});toast('Acesso Gamma salvo.');},value.cycle===n.cycle?'Salvar':'Fechar');break;}
 case 'restart-niche':{const n=byId('niches',data.id);dialog('Novo desenvolvimento de '+n.name,'O ciclo '+n.cycle+' ficará no histórico. O próximo começa com a base inglesa e tarefas pendentes.',area('notes','Motivo do novo desenvolvimento')+`<p class="smallhint wide">Idiomas traduzidos, links, vínculos de lojas e acesso Gamma deste ciclo serão arquivados. Os outros nichos permanecem como estão.</p>`,async(v,command_id)=>{await command({action:'restart_niche',id:n.id,version:n.version,notes:v.notes,command_id});tab='overview';navigate('niche',n.id);toast('Novo ciclo iniciado. O anterior está em Ciclos anteriores.');},'Iniciar ciclo zerado');break;}
 case 'set-language-status':{const l=byId('languages',data.id);dialog('Situação de '+l.name,'Ative os idiomas que estão atendendo às expectativas. Desative os demais.',select('operational_status','Situação',[['preparing','Em preparação'],['active','Ativo'],['inactive','Desativado']],l.operational_status)+area('notes','Observações',l.notes),async(v,command_id)=>{await command({action:'update',entity:'languages',id:l.id,version:l.version,values:v,command_id});toast('Situação do idioma atualizada.');});break;}
 case 'migrate-language':{const l=byId('languages',data.id),sources=state.shops.filter(s=>state.launches.some(x=>x.language_id===l.id&&x.shop_id===s.id)&&l.operational_status==='active');if(!sources.length)return toast('Marque o idioma como ativo e vincule a Shopify de origem antes de planejar a migração.',true);dialog('Planejar migração de '+l.name,'Reutilize a tradução existente e publique somente o idioma marcado como ativo.',select('from_shop_id','Shopify de origem',sources.map(s=>[s.id,s.name]))+select('to_shop_id','Shopify de destino',state.shops.filter(s=>s.active).map(s=>[s.id,s.name]))+ownerField(null)+area('notes','O que a pessoa deverá migrar?'),async(v,command_id)=>{await command({action:'create_migration',language_id:l.id,...v,command_id});toast('Migração criada com responsável e checklist de publicação.');});break;}
 case 'show-cycle':{const c=byId('niche_cycles',data.id),h=await request('history?id='+encodeURIComponent(c.id));dialog('Histórico · ciclo '+c.cycle,'Retrato do ciclo anterior, preservado no novo desenvolvimento.',`<div class="wide historical"><h3>Idiomas e lojas</h3>${h.languages.map(l=>`<p><strong>${esc(l.name)}</strong> · ${h.launches.filter(x=>x.language_id===l.id).map(x=>esc(byId('shops',x.shop_id)?.name)+' ('+esc(labels[x.status])+')').join(', ')||'Sem loja vinculada'}</p>`).join('')}<h3>Trabalho realizado</h3><p>${h.tasks.filter(t=>t.status==='done').length} de ${h.tasks.length} tarefas concluídas.</p>${h.tasks.map(t=>`<p>${esc(t.title)} · ${esc(labels[t.status])} · ${esc(byId('users',t.owner_id)?.name||'Sem responsável')}</p>`).join('')}<h3>Pastas e acessos do ciclo</h3>${h.languages.filter(l=>l.wave==='base').map(l=>[['Entregáveis',l.deliverables_url],['Criativos',l.creatives_url],['Imagens do site',l.site_images_url],['Área de membros',l.member_url]].map(([name,url])=>`<p>${esc(name)}: ${link(url,'Abrir pasta')}</p>`).join('')).join('')}<h3>Situação dos idiomas</h3>${h.languages.map(l=>`<p>${esc(l.name)} · ${esc(performanceLabel(l))}</p>`).join('')}</div>`,async()=>{},'Fechar');break;}
 case 'export-cycle':{const c=byId('niche_cycles',data.id),h=await request('history?id='+encodeURIComponent(c.id));downloadJSON(h,'nicho-'+c.niche_id+'-ciclo-'+c.cycle+'.json');break;}
 case 'logout':await request('logout',{});state=null;renderLogin();break;
 case 'refresh':await refresh();toast(online?'Dados atualizados.':'Sem conexão. Tente novamente.',!online);break;
 case 'toggle-archived':showArchived=!showArchived;render();break;
 case 'new-niche':nicheForm();break;case 'edit-niche':nicheForm(data.id);break;
 case 'new-language':languageForm(null,data.id,data.wave);break;case 'edit-language':languageForm(data.id);break;case 'edit-resources':resourcesForm(data.id);break;
 case 'new-launch':launchForm(null,data.id);break;case 'edit-launch':launchForm(data.id);break;
 case 'new-task':taskForm(null,data.scope,data.id);break;case 'edit-task':taskForm(data.id);break;
 case 'new-shop':shopForm();break;case 'edit-shop':shopForm(data.id);break;
 case 'toggle-task':{const t=byId('tasks',data.id);await command({action:'update',entity:'tasks',id:t.id,version:t.version,values:{status:t.status==='done'?'todo':'done'}});toast(t.status==='done'?'Tarefa reaberta.':'Tarefa concluída.');break;}
 case 'clone-language':{const l=byId('languages',data.id),o=byId('offers',l.offer_id);dialog('Criar outro idioma',`Reaproveite a estrutura de ${l.name}. Cada tarefa começará pendente, com links novos a preencher.`,input('name','Nome do novo idioma','','text','required')+input('code','Código do idioma','','text','required placeholder="Ex.: fr"')+select('wave','Etapa',[['pilot','Tradução integral'],['expansion','Tradução adicional']],o.validated_at?'expansion':'pilot'),async(v,command_id)=>{const result=await command({action:'clone_language',id:l.id,...v,command_id});navigate('language',result.id);toast('Estrutura do idioma criada.');});break;}
 case 'new-user':dialog('Adicionar pessoa','Esta pessoa poderá editar os nichos, ofertas, materiais e tarefas da operação.',input('name','Nome da pessoa','','text','required')+input('email','E-mail identificador (opcional)','','email'),async(v,command_id)=>{const r=await command({action:'create_user',...v,command_id});showAccess(r);},'Criar acesso');break;
 case 'rotate-user':{const p=byId('users',data.id);dialog('Gerar novo link',p.name+' · O novo link substituirá o anterior e encerrará as sessões antigas.',`<p class="wide">${p.id===state.me.id?'Guarde o novo link e abra-o para continuar usando sua conta.':'Copie e compartilhe o novo acesso com essa pessoa.'}</p>`,async(v,command_id)=>{const r=await command({action:'rotate_link',id:p.id,command_id});showAccess(r);},'Gerar novo link');break;}
 case 'disable-user':{const p=byId('users',data.id);dialog('Desativar acesso',p.name+' · O histórico e as tarefas serão preservados.',`<p class="wide">Esta pessoa deixará de acessar o espaço. Você poderá reativá-la gerando outro link.</p>`,async(v,command_id)=>{await command({action:'disable_user',id:p.id,command_id});toast('Acesso desativado.');},'Desativar');break;}
 case 'export':{const value=await request('export');const file=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=file;a.download='offervault-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(file),1000);toast('Dados exportados.');break;}
 case 'close-modal':if(!saving&&!importing)modalRoot.innerHTML='';break;
 }
}
function downloadJSON(value,name){const file=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=file;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(file),1000);}
document.addEventListener('click',e=>{const target=e.target.closest('button');if(!target)return;if(target.dataset.screen){navigate(target.dataset.screen,target.dataset.id);return;}if(target.dataset.tab){tab=target.dataset.tab;render();return;}if(target.dataset.action){void act(target.dataset.action,target.dataset).catch(err=>toast(err.message,true));}});
document.addEventListener('input',e=>{if(e.target.matches('[data-global-search]')){const start=e.target.selectionStart;search=e.target.value;screen='search';render();const input=document.querySelector('[data-global-search]');input?.focus();input?.setSelectionRange(start,start);return;}if(e.target.matches('[data-search]')){const start=e.target.selectionStart;search=e.target.value;render();const input=document.querySelector('[data-search]');input?.focus();input?.setSelectionRange(start,start);}});
document.addEventListener('change',e=>{if(e.target.matches('[data-language-shop],[data-language-facebook]')){const el=e.target,l=byId('languages',el.dataset.languageShop||el.dataset.languageFacebook);const body=el.dataset.languageShop?{action:'configure_language',id:l.id,version:l.version,values:{},shop_id:el.dataset.shop,enabled:el.checked}:{action:'update',entity:'languages',id:l.id,version:l.version,values:{facebook:el.checked?1:0}};el.disabled=true;void command(body).catch(err=>{render();toast(err.message,true);});return;}if(e.target.id==='task-filter'){taskFilter=e.target.value;render();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!saving&&!importing)modalRoot.innerHTML='';if(e.key==='Tab'&&modalRoot.childElementCount){const items=[...modalRoot.querySelectorAll('button:not(:disabled),input,select,textarea,a[href]')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
window.addEventListener('hashchange',authenticate);window.addEventListener('online',()=>refresh());window.addEventListener('offline',()=>{online=false;updateConnection();});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state)void refresh();});
setInterval(()=>{if(state&&!saving)void refresh();},10000);void authenticate();
