CREATE TABLE IF NOT EXISTS categories(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,color TEXT NOT NULL DEFAULT '#91dfba',version INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value INTEGER NOT NULL);
INSERT OR IGNORE INTO meta VALUES('revision',0);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL DEFAULT '',role TEXT NOT NULL CHECK(role IN ('owner','member')),active INTEGER NOT NULL DEFAULT 1,link_hash TEXT UNIQUE,version INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS niches(id TEXT PRIMARY KEY,name TEXT NOT NULL,category TEXT NOT NULL DEFAULT '',category_id TEXT REFERENCES categories(id),description TEXT NOT NULL DEFAULT '',audience TEXT NOT NULL DEFAULT '',owner_id TEXT REFERENCES users(id),priority TEXT NOT NULL DEFAULT 'normal',stage TEXT NOT NULL DEFAULT 'idea',tags TEXT NOT NULL DEFAULT '',cover_url TEXT NOT NULL DEFAULT '',commercial_model TEXT NOT NULL DEFAULT 'Compra única · produto digital',notes TEXT NOT NULL DEFAULT '',archived INTEGER NOT NULL DEFAULT 0,cycle INTEGER NOT NULL DEFAULT 1,version INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS offers(id TEXT PRIMARY KEY,niche_id TEXT NOT NULL REFERENCES niches(id),name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',phase TEXT NOT NULL DEFAULT 'production',cycle INTEGER NOT NULL DEFAULT 1,owner_id TEXT REFERENCES users(id),pilot_target INTEGER NOT NULL DEFAULT 5,validated_at INTEGER,validation_note TEXT NOT NULL DEFAULT '',version INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS languages(id TEXT PRIMARY KEY,offer_id TEXT NOT NULL REFERENCES offers(id),code TEXT NOT NULL,name TEXT NOT NULL,wave TEXT NOT NULL DEFAULT 'pilot',operational_status TEXT NOT NULL DEFAULT 'preparing',facebook INTEGER NOT NULL DEFAULT 0,notes TEXT NOT NULL DEFAULT '',owner_id TEXT REFERENCES users(id),member_url TEXT NOT NULL DEFAULT '',deliverables_url TEXT NOT NULL DEFAULT '',creatives_url TEXT NOT NULL DEFAULT '',site_images_url TEXT NOT NULL DEFAULT '',version INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(offer_id,code));
CREATE TABLE IF NOT EXISTS shops(id TEXT PRIMARY KEY,name TEXT NOT NULL,domain TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 1,version INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS launches(id TEXT PRIMARY KEY,language_id TEXT NOT NULL REFERENCES languages(id),shop_id TEXT NOT NULL REFERENCES shops(id),status TEXT NOT NULL DEFAULT 'preparing',enabled INTEGER NOT NULL DEFAULT 1,product_url TEXT NOT NULL DEFAULT '',page_url TEXT NOT NULL DEFAULT '',checkout_url TEXT NOT NULL DEFAULT '',campaign_url TEXT NOT NULL DEFAULT '',campaign_name TEXT NOT NULL DEFAULT '',product_id TEXT NOT NULL DEFAULT '',variant_id TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',owner_id TEXT REFERENCES users(id),version INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(language_id,shop_id));
CREATE TABLE IF NOT EXISTS gamma_accounts(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL DEFAULT '',workspace_url TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 1,version INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS niche_gamma(niche_id TEXT NOT NULL REFERENCES niches(id),gamma_id TEXT NOT NULL REFERENCES gamma_accounts(id),cycle INTEGER NOT NULL DEFAULT 1,PRIMARY KEY(niche_id,gamma_id,cycle));
CREATE TABLE IF NOT EXISTS deliverables(id TEXT PRIMARY KEY,offer_id TEXT NOT NULL REFERENCES offers(id),language_id TEXT REFERENCES languages(id),gamma_id TEXT REFERENCES gamma_accounts(id),title TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'book',status TEXT NOT NULL DEFAULT 'todo',gamma_url TEXT NOT NULL DEFAULT '',final_url TEXT NOT NULL DEFAULT '',edition TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',owner_id TEXT REFERENCES users(id),version INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY,offer_id TEXT NOT NULL REFERENCES offers(id),scope TEXT NOT NULL,scope_id TEXT NOT NULL,template_key TEXT NOT NULL DEFAULT '',title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'todo',owner_id TEXT REFERENCES users(id),due_date TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',blocked_reason TEXT NOT NULL DEFAULT '',result_url TEXT NOT NULL DEFAULT '',position INTEGER NOT NULL DEFAULT 0,version INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS task_templates ON tasks(scope,scope_id,template_key) WHERE template_key<>'';
CREATE TABLE IF NOT EXISTS activity(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),entity TEXT NOT NULL,entity_id TEXT NOT NULL,action TEXT NOT NULL,summary TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS activity_time ON activity(created_at);
CREATE TABLE IF NOT EXISTS commands(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),fingerprint TEXT NOT NULL,result TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS login_limits(key TEXT PRIMARY KEY,attempts INTEGER NOT NULL,until_at INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS niche_cycles(id TEXT PRIMARY KEY,niche_id TEXT NOT NULL REFERENCES niches(id),cycle INTEGER NOT NULL,notes TEXT NOT NULL,snapshot TEXT NOT NULL,restarted_by TEXT NOT NULL REFERENCES users(id),created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS migrations(id TEXT PRIMARY KEY,language_id TEXT NOT NULL REFERENCES languages(id),from_shop_id TEXT NOT NULL REFERENCES shops(id),to_shop_id TEXT NOT NULL REFERENCES shops(id),launch_id TEXT NOT NULL REFERENCES launches(id),task_id TEXT NOT NULL REFERENCES tasks(id),notes TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),created_at INTEGER NOT NULL);

CREATE INDEX IF NOT EXISTS offers_niche_cycle ON offers(niche_id,cycle);
CREATE INDEX IF NOT EXISTS languages_offer ON languages(offer_id);
CREATE INDEX IF NOT EXISTS tasks_owner_status ON tasks(owner_id,status);
CREATE INDEX IF NOT EXISTS launches_shop_status ON launches(shop_id,status);
CREATE INDEX IF NOT EXISTS deliverables_gamma ON deliverables(gamma_id);
CREATE TABLE IF NOT EXISTS niche_secrets(niche_id TEXT NOT NULL REFERENCES niches(id),cycle INTEGER NOT NULL,encrypted_text TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,updated_by TEXT NOT NULL REFERENCES users(id),updated_at INTEGER NOT NULL,PRIMARY KEY(niche_id,cycle));
-- Migration 2: additive provenance records; existing operational data is preserved.
CREATE TABLE IF NOT EXISTS trello_sources(id TEXT PRIMARY KEY,card_id TEXT NOT NULL UNIQUE,card_url TEXT NOT NULL,niche_id TEXT NOT NULL REFERENCES niches(id),cycle INTEGER NOT NULL,shop_id TEXT NOT NULL REFERENCES shops(id),payload_hash TEXT NOT NULL,imported_by TEXT NOT NULL REFERENCES users(id),imported_at INTEGER NOT NULL,source_name TEXT NOT NULL);
