name: Deploy to VPS

on:
  push:
    branches:
      - main
    paths:
      - 'bible1/**'
      - 'bible1-members/**'
      - 'bible1-es/**'
      - 'bible1-it/**'
      - 'sc/**'
      - 'sc-es/**'
      - 'sc-it/**'
      - 'sc-pt/**'
      - 'py/**'
      - 'py-es/**'
      - 'py-fr/**'
      - 'smoothies/**'
      - 'smoothies-members/**'
      - 'chickens/**'
      - 'chickens-de/**'
      - 'Página modelo/**'
      - 'WW/**'
      - 'ww-de/**'
      - 'ww-fr/**'
      - 'ww-it/**'
      - 'ww-plans-fr/**'
      - 'ww-plans-it/**'
      - 'mw-de/**'
      - 'mw/**'
      - 'mw-pt/**'
      - 'bkp/**'
      - 'bkp-de/**'
      - 'bkp-es/**'
      - 'bkp-pt/**'
      - 'hx-fr/**'
      - 'hx-it/**'
      - 'beekeeping-members/**'
      - 'beekeeping-de-members/**'
      - 'beekeeping-fr-members/**'
      - 'beekeeping-it-members/**'
      - 'beekeeping-es-members/**'
      - 'beekeeping-pt-members/**'
      - 'beekeeping-nl-members/**'
      - 'beekeeping-pl-members/**'
      - 'beekeeping-cs-members/**'
      - 'beekeeping-el-members/**'
      - 'beekeeping-ro-members/**'
      - 'beekeeping-hu-members/**'
      - 'ww-members/**'
      - 'ww-de-members/**'
      - 'metalon-members/**'
      - 'excel/**'
      - 'excel-plans-fr/**'
      - 'excel-plans-de/**'
      - 'excel-plans-es/**'
      - 'excel-plans-it/**'
      - 'excel-plans-pt/**'
      - 'excel-members/**'
      - 'excel-de-members/**'
      - 'excel-pl-members/**'
      - 'excel-fr-members/**'
      - 'excel-es-members/**'
      - 'excel-it-members/**'
      - 'excel-pt-members/**'
      - 'off-grid/**'
      - 'off-grid-fr/**'
      - 'off-grid-de/**'
      - 'off-grid-members/**'
      - 'off-grid-de-members/**'
      - 'off-grid-fr-members/**'
      - 'natures/**'
      - 'natures-de/**'
      - 'natures-fr/**'
      - 'natures-de-members/**'
      - 'natures-da-members/**'
      - 'natures-nl-members/**'
      - 'natures-hu-members/**'
      - 'natures-pl-members/**'
      - 'natures-es-members/**'
      - 'nature-he-members/**'
      - 'nature-ar-members/**'
      - 'nature-ru-members/**'
      - 'nature-tr-members/**'
      - 'nature-lt-members/**'
      - 'Fishing/**'
      - 'Fishing-de/**'
      - 'Fishing-fr/**'
      - '.github/workflows/**'

      - 'nature-el-members/**'
      - 'nature-uk-members/**'
      - 'nature-ro-members/**'
      - 'nature-bs-members/**'
      - 'nature-ca-members/**'
      - 'nature-zh-members/**'
      - 'nature-ko-members/**'
      - 'nature-ja-members/**'
      - 'nature-lv-members/**'
      - 'nature-mk-members/**'
      - 'nature-sr-members/**'
      - 'nature-members-es/**'
      - 'nature-members/**'
      - 'nature-sv-members/**'
      - 'nature-sl-members/**'
      - 'nature-sk-members/**'
      - 'natures-sk-members/**'
      - 'nature-pt-members/**'
      - 'nature-pl-members/**'
      - 'nature-no-members/**'
      - 'nature-nl-members/**'
      - 'nature-members-it/**'
      - 'nature-hu-members/**'
      - 'nature-hr-members/**'
      - 'nature-fr-members/**'
      - 'nature-fi-members/**'
      - 'nature-de-members/**'
      - 'nature-da-members/**'
      - 'nature-cs-members/**'
      - 'nature-bg-members/**'
      - 'gfree-members/**'
      - 'gfree-pl-members/**'
      - 'gfree-nl-members/**'
      - 'gfree-de-members/**'
      - 'gfree-da-members/**'
      - 'gfree-en-members/**'
      - 'gfree-el-members/**'
      - 'gfree-fr-members/**'
      - 'gfree-it-members/**'
      - 'gfree-es-members/**'
      - 'gfree-hr-members/**'
      - 'gfree-fi-members/**'
      - 'gfree-ar-members/**'
      - 'gfree-bg-members/**'
      - 'gfree-hu-members/**'
      - 'gfree-no-members/**'
      - 'gfree-ga-members/**'
      - 'gfree-ro-members/**'
      - 'gfree-sr-members/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false

      - name: Pull LFS for changed directories
        run: |
          BEFORE_SHA="${{ github.event.before }}"
          AFTER_SHA="${{ github.event.after }}"
          if [ -z "$BEFORE_SHA" ] || [ "$BEFORE_SHA" = "0000000000000000000000000000000000000000" ]; then
            if git rev-parse HEAD~1 >/dev/null 2>&1; then
              BEFORE_SHA="HEAD~1"
            else
              BEFORE_SHA=""
            fi
          fi
          if [ -z "$BEFORE_SHA" ]; then
            echo "No base commit found for diff. Pulling all LFS files."
            git lfs pull
          else
            DIRS=""
            for item in $(git diff --name-only "$BEFORE_SHA" "$AFTER_SHA" | cut -d/ -f1 | sort -u); do
              if [ -d "$item" ]; then
                if [ -z "$DIRS" ]; then
                  DIRS="$item"
                else
                  DIRS="$DIRS,$item"
                fi
              fi
            done
            if [ -n "$DIRS" ]; then
              INCLUDE_PATTERN=$(echo "$DIRS" | sed 's/,/\/\*\*,/g' | sed 's/$/\/\*\*/')
              echo "Pulling LFS files for: $INCLUDE_PATTERN"
              git lfs pull --include="$INCLUDE_PATTERN"
            else
              echo "No directories changed. Skipping LFS pull."
            fi
          fi

      - name: Check changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            off-grid:
              - 'off-grid/**'
            off-grid-fr:
              - 'off-grid-fr/**'
            off-grid-de:
              - 'off-grid-de/**'
            off-grid-members:
              - 'off-grid-members/**'
            off-grid-de-members:
              - 'off-grid-de-members/**'
            off-grid-fr-members:
              - 'off-grid-fr-members/**'
            bible1:
              - 'bible1/**'
            bible1-members:
              - 'bible1-members/**'
            bible1-es:
              - 'bible1-es/**'
            bible1-it:
              - 'bible1-it/**'
            sc:
              - 'sc/**'
            sc-es:
              - 'sc-es/**'
            sc-it:
              - 'sc-it/**'
            sc-pt:
              - 'sc-pt/**'
            py:
              - 'py/**'
            py-es:
              - 'py-es/**'
            py-fr:
              - 'py-fr/**'
            smoothies:
              - 'smoothies/**'
            smoothies-members:
              - 'smoothies-members/**'
            pagina_modelo:
              - 'Página modelo/**'
            natures:
              - 'natures/**'
            natures-de:
              - 'natures-de/**'
            natures-fr:
              - 'natures-fr/**'
            natures-de-members:
              - 'natures-de-members/**'
            natures-da-members:
              - 'natures-da-members/**'
            natures-nl-members:
              - 'natures-nl-members/**'
            natures-hu-members:
              - 'natures-hu-members/**'
            natures-pl-members:
              - 'natures-pl-members/**'
            natures-es-members:
              - 'natures-es-members/**'
            nature-he-members:
              - 'nature-he-members/**'
            nature-members-es:
              - 'nature-members-es/**'
            nature-members:
              - 'nature-members/**'
            nature-el-members:
              - 'nature-el-members/**'
            nature-uk-members:
              - 'nature-uk-members/**'
            nature-ro-members:
              - 'nature-ro-members/**'
            nature-bs-members:
              - 'nature-bs-members/**'
            nature-ca-members:
              - 'nature-ca-members/**'
            nature-ar-members:
              - 'nature-ar-members/**'
            nature-ru-members:
              - 'nature-ru-members/**'
            nature-tr-members:
              - 'nature-tr-members/**'
            nature-lt-members:
              - 'nature-lt-members/**'
            nature-zh-members:
              - 'nature-zh-members/**'
            nature-ko-members:
              - 'nature-ko-members/**'
            nature-ja-members:
              - 'nature-ja-members/**'
            nature-lv-members:
              - 'nature-lv-members/**'
            nature-mk-members:
              - 'nature-mk-members/**'
            nature-sr-members:
              - 'nature-sr-members/**'

            nature-sv-members:
              - 'nature-sv-members/**'
            nature-sl-members:
              - 'nature-sl-members/**'
            nature-sk-members:
              - 'nature-sk-members/**'
            natures-sk-members:
              - 'natures-sk-members/**'
            nature-pt-members:
              - 'nature-pt-members/**'
            nature-pl-members:
              - 'nature-pl-members/**'
            nature-no-members:
              - 'nature-no-members/**'
            nature-nl-members:
              - 'nature-nl-members/**'
            nature-members-it:
              - 'nature-members-it/**'
            nature-hu-members:
              - 'nature-hu-members/**'
            nature-hr-members:
              - 'nature-hr-members/**'
            nature-fr-members:
              - 'nature-fr-members/**'
            nature-fi-members:
              - 'nature-fi-members/**'
            nature-de-members:
              - 'nature-de-members/**'
            nature-da-members:
              - 'nature-da-members/**'
            nature-cs-members:
              - 'nature-cs-members/**'
            nature-bg-members:
              - 'nature-bg-members/**'
            gfree-members:
              - 'gfree-members/**'
            gfree-pl-members:
              - 'gfree-pl-members/**'
            gfree-nl-members:
              - 'gfree-nl-members/**'
            gfree-de-members:
              - 'gfree-de-members/**'
            gfree-da-members:
              - 'gfree-da-members/**'
            gfree-en-members:
              - 'gfree-en-members/**'
            gfree-el-members:
              - 'gfree-el-members/**'
            gfree-fr-members:
              - 'gfree-fr-members/**'
            gfree-it-members:
              - 'gfree-it-members/**'
            gfree-es-members:
              - 'gfree-es-members/**'
            gfree-hr-members:
              - 'gfree-hr-members/**'
            gfree-fi-members:
              - 'gfree-fi-members/**'
            gfree-ar-members:
              - 'gfree-ar-members/**'
            gfree-bg-members:
              - 'gfree-bg-members/**'
            gfree-hu-members:
              - 'gfree-hu-members/**'
            gfree-no-members:
              - 'gfree-no-members/**'
            gfree-ga-members:
              - 'gfree-ga-members/**'
            gfree-ro-members:
              - 'gfree-ro-members/**'
            gfree-sr-members:
              - 'gfree-sr-members/**'
            fishing:
              - 'Fishing/**'
            fishing-de:
              - 'Fishing-de/**'
            fishing-fr:
              - 'Fishing-fr/**'
            ww:
              - 'WW/**'
            chickens:
              - 'chickens/**'
            chickens-de:
              - 'chickens-de/**'
            ww-de:
              - 'ww-de/**'
            ww-fr:
              - 'ww-fr/**'
            ww-it:
              - 'ww-it/**'
            ww-plans-fr:
              - 'ww-plans-fr/**'
            ww-plans-it:
              - 'ww-plans-it/**'
            mw-de:
              - 'mw-de/**'
            mw:
              - 'mw/**'
            mw-pt:
              - 'mw-pt/**'
            bkp:
              - 'bkp/**'
            bkp-de:
              - 'bkp-de/**'
            bkp-es:
              - 'bkp-es/**'
            bkp-pt:
              - 'bkp-pt/**'
            hx-fr:
              - 'hx-fr/**'
            hx-it:
              - 'hx-it/**'
            beekeeping-members:
              - 'beekeeping-members/**'
            beekeeping-de-members:
              - 'beekeeping-de-members/**'
            beekeeping-fr-members:
              - 'beekeeping-fr-members/**'
            beekeeping-it-members:
              - 'beekeeping-it-members/**'
            beekeeping-es-members:
              - 'beekeeping-es-members/**'
            beekeeping-pt-members:
              - 'beekeeping-pt-members/**'
            beekeeping-nl-members:
              - 'beekeeping-nl-members/**'
            beekeeping-pl-members:
              - 'beekeeping-pl-members/**'
            beekeeping-cs-members:
              - 'beekeeping-cs-members/**'
            beekeeping-el-members:
              - 'beekeeping-el-members/**'
            beekeeping-ro-members:
              - 'beekeeping-ro-members/**'
            beekeeping-hu-members:
              - 'beekeeping-hu-members/**'
            ww-members:
              - 'ww-members/**'
            ww-de-members:
              - 'ww-de-members/**'
            metalon-members:
              - 'metalon-members/**'
            excel:
              - 'excel/**'
            excel-plans-fr:
              - 'excel-plans-fr/**'
            excel-plans-de:
              - 'excel-plans-de/**'
            excel-plans-es:
              - 'excel-plans-es/**'
            excel-plans-it:
              - 'excel-plans-it/**'
            excel-plans-pt:
              - 'excel-plans-pt/**'
            excel-members:
              - 'excel-members/**'
            excel-de-members:
              - 'excel-de-members/**'
            excel-pl-members:
              - 'excel-pl-members/**'
            excel-fr-members:
              - 'excel-fr-members/**'
            excel-es-members:
              - 'excel-es-members/**'
            excel-it-members:
              - 'excel-it-members/**'
            excel-pt-members:
              - 'excel-pt-members/**'

      - name: Prepare VPS Directories for Deployments
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          script: |
            sudo mkdir -p /var/www/storeinfocus.com/bible1
            sudo mkdir -p /var/www/storeinfocus.com/bible1-members
            sudo mkdir -p /var/www/storeinfocus.com/bible1-es
            sudo mkdir -p /var/www/storeinfocus.com/bible1-it
            sudo mkdir -p /var/www/storeinfocus.com/sc
            sudo mkdir -p /var/www/storeinfocus.com/sc-es
            sudo mkdir -p /var/www/storeinfocus.com/sc-it
            sudo mkdir -p /var/www/storeinfocus.com/sc-pt
            sudo mkdir -p /var/www/storeinfocus.com/py
            sudo mkdir -p /var/www/storeinfocus.com/py-es
            sudo mkdir -p /var/www/storeinfocus.com/py-fr
            sudo mkdir -p /var/www/storeinfocus.com/smoot
            sudo mkdir -p /var/www/storeinfocus.com/smoot-m
            sudo mkdir -p /var/www/storeinfocus.com/pagina-modelo
            sudo mkdir -p /var/www/storeinfocus.com/nature
            sudo mkdir -p /var/www/storeinfocus.com/nature-de
            sudo mkdir -p /var/www/storeinfocus.com/nature-fr
            sudo mkdir -p /var/www/storeinfocus.com/natures-de-members
            sudo mkdir -p /var/www/storeinfocus.com/natures-da-members
            sudo mkdir -p /var/www/storeinfocus.com/natures-nl-members
            sudo mkdir -p /var/www/storeinfocus.com/natures-hu-members
            sudo mkdir -p /var/www/storeinfocus.com/natures-pl-members
            sudo mkdir -p /var/www/storeinfocus.com/natures-es-members
            sudo mkdir -p /var/www/storeinfocus.com/fish
            sudo mkdir -p /var/www/storeinfocus.com/fish-de
            sudo mkdir -p /var/www/storeinfocus.com/fish-fr
            sudo chown -R ${{ secrets.VPS_USERNAME }}:${{ secrets.VPS_USERNAME }} /var/www/storeinfocus.com || true
            sudo mkdir -p /var/www/skillvault.blog/nature-members-es
            sudo mkdir -p /var/www/skillvault.blog/nature-members-sv
            sudo mkdir -p /var/www/skillvault.blog/nature-members-sl
            sudo mkdir -p /var/www/skillvault.blog/nature-members-sk
            sudo mkdir -p /var/www/skillvault.blog/nature-members-pt
            sudo mkdir -p /var/www/skillvault.blog/nature-members-pl
            sudo mkdir -p /var/www/skillvault.blog/nature-members-no
            sudo mkdir -p /var/www/skillvault.blog/nature-members-nl
            sudo mkdir -p /var/www/skillvault.blog/nature-members-it
            sudo mkdir -p /var/www/skillvault.blog/nature-members-hu
            sudo mkdir -p /var/www/skillvault.blog/nature-members-hr
            sudo mkdir -p /var/www/skillvault.blog/nature-members-fr
            sudo mkdir -p /var/www/skillvault.blog/nature-members-ar
            sudo mkdir -p /var/www/skillvault.blog/nature-members-ru
            sudo mkdir -p /var/www/skillvault.blog/nature-members-tr
            sudo mkdir -p /var/www/skillvault.blog/nature-members-lt
            sudo mkdir -p /var/www/skillvault.blog/nature-members-fi
            sudo mkdir -p /var/www/skillvault.blog/nature-members-de
            sudo mkdir -p /var/www/skillvault.blog/nature-members-da
            sudo mkdir -p /var/www/skillvault.blog/nature-members-cs
            sudo mkdir -p /var/www/skillvault.blog/nature-members-bg
            sudo mkdir -p /var/www/skillvault.blog/nature-members-bs
            sudo mkdir -p /var/www/skillvault.blog/nature-members-ca
            sudo mkdir -p /var/www/skillvault.blog/nature-members-zh
            sudo mkdir -p /var/www/skillvault.blog/nature-members-ko
            sudo mkdir -p /var/www/skillvault.blog/nature-members-ja
            sudo mkdir -p /var/www/skillvault.blog/nature-members-lv
            sudo mkdir -p /var/www/skillvault.blog/nature-members-mk
            sudo mkdir -p /var/www/skillvault.blog/nature-members-sr
            sudo mkdir -p /var/www/skillvault.blog/nature-members-ro
            sudo mkdir -p /var/www/skillvault.blog/ww
            sudo mkdir -p /var/www/skillvault.blog/chickens
            sudo mkdir -p /var/www/skillvault.blog/chickens-al
            sudo mkdir -p /var/www/skillvault.blog/ww-de
            sudo mkdir -p /var/www/skillvault.blog/ww-fr
            sudo mkdir -p /var/www/skillvault.blog/ww-it
            sudo mkdir -p /var/www/skillvault.blog/ww-plans-fr
            sudo mkdir -p /var/www/skillvault.blog/ww-plans-it
            sudo mkdir -p /var/www/skillvault.blog/mw-de
            sudo mkdir -p /var/www/skillvault.blog/mw
            sudo mkdir -p /var/www/skillvault.blog/mw-pt
            sudo mkdir -p /var/www/skillvault.blog/bkp
            sudo mkdir -p /var/www/skillvault.blog/bkp-de
            sudo mkdir -p /var/www/skillvault.blog/bkp-es
            sudo mkdir -p /var/www/skillvault.blog/bkp-pt
            sudo mkdir -p /var/www/skillvault.blog/hx-fr
            sudo mkdir -p /var/www/skillvault.blog/hx-it
            sudo mkdir -p /var/www/skillvault.blog/bkp-m
            sudo mkdir -p /var/www/skillvault.blog/bkp-de-m
            sudo mkdir -p /var/www/skillvault.blog/hx-fr-m
            sudo mkdir -p /var/www/skillvault.blog/hx-it-m
            sudo mkdir -p /var/www/skillvault.blog/hx-es-m
            sudo mkdir -p /var/www/skillvault.blog/hx-pt-m
            sudo mkdir -p /var/www/skillvault.blog/bkp-nl-m
            sudo mkdir -p /var/www/skillvault.blog/bkp-pl-m
            sudo mkdir -p /var/www/skillvault.blog/bkp-cs-m
            sudo mkdir -p /var/www/skillvault.blog/bkp-el-m
            sudo mkdir -p /var/www/skillvault.blog/bkp-ro-m
            sudo mkdir -p /var/www/skillvault.blog/bkp-hu-m
            sudo mkdir -p /var/www/skillvault.blog/ww-m
            sudo mkdir -p /var/www/skillvault.blog/ww-de-m
            sudo mkdir -p /var/www/skillvault.blog/mw-m
            sudo mkdir -p /var/www/skillvault.blog/excel
            sudo mkdir -p /var/www/skillvault.blog/excel-plans-fr
            sudo mkdir -p /var/www/skillvault.blog/excel-plans-de
            sudo mkdir -p /var/www/skillvault.blog/excel-plans-es
            sudo mkdir -p /var/www/skillvault.blog/excel-plans-it
            sudo mkdir -p /var/www/skillvault.blog/excel-plans-pt
            sudo mkdir -p /var/www/skillvault.blog/excel-m
            sudo mkdir -p /var/www/skillvault.blog/excel-de-m
            sudo mkdir -p /var/www/skillvault.blog/excel-pl-m
            sudo mkdir -p /var/www/skillvault.blog/excel-fr-m
            sudo mkdir -p /var/www/skillvault.blog/excel-es-m
            sudo mkdir -p /var/www/skillvault.blog/excel-it-m
            sudo mkdir -p /var/www/skillvault.blog/excel-pt-m
            sudo mkdir -p /var/www/skillvault.blog/off-grid
            sudo mkdir -p /var/www/skillvault.blog/off-grid-fr
            sudo mkdir -p /var/www/skillvault.blog/off-grid-de
            sudo mkdir -p /var/www/skillvault.blog/off-products
            sudo mkdir -p /var/www/skillvault.blog/off-products-de
            sudo mkdir -p /var/www/skillvault.blog/off-products-fr
            sudo mkdir -p /var/www/skillvault.blog/natural-members-he
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-sv
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-pl
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-nl
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-de
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-da
            sudo mkdir -p /var/www/naturalmethods.blog/g-free
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-el
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-fr
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-it
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-es
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-hr
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-fi
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-ar
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-bg
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-hu
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-no
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-ga
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-ro
            sudo mkdir -p /var/www/naturalmethods.blog/g-free-sr
            sudo chown -R ${{ secrets.VPS_USERNAME }}:${{ secrets.VPS_USERNAME }} /var/www/skillvault.blog || true
            sudo chmod -R 755 /var/www/skillvault.blog || true

      # ── OFF GRID ───────────────────────────────────────────────────────────

      - name: Deploy 'off-grid' to skillvault.blog/off-grid
        if: steps.filter.outputs.off-grid == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "off-grid/*"
          target: "/var/www/skillvault.blog/off-grid"
          strip_components: 1

      - name: Deploy 'off-grid-fr' to skillvault.blog/off-grid-fr
        if: steps.filter.outputs.off-grid-fr == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "off-grid-fr/*"
          target: "/var/www/skillvault.blog/off-grid-fr"
          strip_components: 1

      - name: Deploy 'off-grid-de' to skillvault.blog/off-grid-de
        if: steps.filter.outputs.off-grid-de == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "off-grid-de/*"
          target: "/var/www/skillvault.blog/off-grid-de"
          strip_components: 1

      - name: Deploy 'off-grid-members' to skillvault.blog/off-products
        if: steps.filter.outputs.off-grid-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "off-grid-members/*"
          target: "/var/www/skillvault.blog/off-products"
          strip_components: 1

      - name: Deploy 'off-grid-de-members' to skillvault.blog/off-products-de
        if: steps.filter.outputs.off-grid-de-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "off-grid-de-members/*"
          target: "/var/www/skillvault.blog/off-products-de"
          strip_components: 1

      - name: Deploy 'off-grid-fr-members' to skillvault.blog/off-products-fr
        if: steps.filter.outputs.off-grid-fr-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "off-grid-fr-members/*"
          target: "/var/www/skillvault.blog/off-products-fr"
          strip_components: 1

      # ── BIBLE1 ─────────────────────────────────────────────────────────────

      - name: Deploy 'bible1' to storeinfocus.com/bible1
        if: steps.filter.outputs.bible1 == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "bible1/*"
          target: "/var/www/storeinfocus.com/bible1"
          strip_components: 1

      - name: Deploy 'bible1-members' to storeinfocus.com/bible1-members
        if: steps.filter.outputs.bible1-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "bible1-members/*"
          target: "/var/www/storeinfocus.com/bible1-members"
          strip_components: 1

      - name: Deploy 'bible1-es' to storeinfocus.com/bible1-es
        if: steps.filter.outputs.bible1-es == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "bible1-es/*"
          target: "/var/www/storeinfocus.com/bible1-es"
          strip_components: 1

      - name: Deploy 'bible1-it' to storeinfocus.com/bible1-it
        if: steps.filter.outputs.bible1-it == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "bible1-it/*"
          target: "/var/www/storeinfocus.com/bible1-it"
          strip_components: 1

      # â”€â”€ SYSTEMATIC THEOLOGY â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

      - name: Deploy 'sc' to storeinfocus.com/sc
        if: steps.filter.outputs.sc == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "sc/*"
          target: "/var/www/storeinfocus.com/sc"
          strip_components: 1

      - name: Deploy 'sc-es' to storeinfocus.com/sc-es
        if: steps.filter.outputs.sc-es == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "sc-es/*"
          target: "/var/www/storeinfocus.com/sc-es"
          strip_components: 1

      - name: Deploy 'sc-it' to storeinfocus.com/sc-it
        if: steps.filter.outputs.sc-it == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "sc-it/*"
          target: "/var/www/storeinfocus.com/sc-it"
          strip_components: 1

      - name: Deploy 'sc-pt' to storeinfocus.com/sc-pt
        if: steps.filter.outputs.sc-pt == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "sc-pt/*"
          target: "/var/www/storeinfocus.com/sc-pt"
          strip_components: 1

      # â”€â”€ PROSPERITY â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

      - name: Deploy 'py' to storeinfocus.com/py
        if: steps.filter.outputs.py == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "py/*"
          target: "/var/www/storeinfocus.com/py"
          strip_components: 1

      - name: Deploy 'py-es' to storeinfocus.com/py-es
        if: steps.filter.outputs.py-es == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "py-es/*"
          target: "/var/www/storeinfocus.com/py-es"
          strip_components: 1

      - name: Deploy 'py-fr' to storeinfocus.com/py-fr
        if: steps.filter.outputs.py-fr == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "py-fr/*"
          target: "/var/www/storeinfocus.com/py-fr"
          strip_components: 1

      - name: Deploy 'smoothies' to storeinfocus.com/smoot
        if: steps.filter.outputs.smoothies == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "smoothies/*"
          target: "/var/www/storeinfocus.com/smoot"
          strip_components: 1

      - name: Deploy 'smoothies-members' to storeinfocus.com/smoot-m
        if: steps.filter.outputs.smoothies-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "smoothies-members/*"
          target: "/var/www/storeinfocus.com/smoot-m"
          strip_components: 1

      # ── WOODWORKING ─────────────────────────────────────────────────────────────────────────────────

      - name: Deploy 'Página modelo' to storeinfocus.com/pagina-modelo
        if: steps.filter.outputs.pagina_modelo == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "Página modelo/*"
          target: "/var/www/storeinfocus.com/pagina-modelo"
          strip_components: 1

      # ── APOTHECARY & FISHING ──────────────────────────────────────────────────────────────────────────

      - name: Deploy 'natures' to storeinfocus.com/nature
        if: steps.filter.outputs.natures == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "natures/*"
          target: "/var/www/storeinfocus.com/nature"
          strip_components: 1

      - name: Deploy 'natures-de' to storeinfocus.com/nature-de
        if: steps.filter.outputs.natures-de == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "natures-de/*"
          target: "/var/www/storeinfocus.com/nature-de"
          strip_components: 1

      - name: Deploy 'natures-fr' to storeinfocus.com/nature-fr
        if: steps.filter.outputs.natures-fr == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "natures-fr/*"
          target: "/var/www/storeinfocus.com/nature-fr"
          strip_components: 1

      - name: Deploy 'natures-de-members' to storeinfocus.com/natures-de-members
        if: steps.filter.outputs.natures-de-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "natures-de-members/*"
          target: "/var/www/storeinfocus.com/natures-de-members"
          strip_components: 1

      - name: Deploy 'natures-da-members' to storeinfocus.com/natures-da-members
        if: steps.filter.outputs.natures-da-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "natures-da-members/*"
          target: "/var/www/storeinfocus.com/natures-da-members"
          strip_components: 1

      - name: Deploy 'natures-nl-members' to storeinfocus.com/natures-nl-members
        if: steps.filter.outputs.natures-nl-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "natures-nl-members/*"
          target: "/var/www/storeinfocus.com/natures-nl-members"
          strip_components: 1

      - name: Deploy 'natures-hu-members' to storeinfocus.com/natures-hu-members
        if: steps.filter.outputs.natures-hu-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "natures-hu-members/*"
          target: "/var/www/storeinfocus.com/natures-hu-members"
          strip_components: 1

      - name: Deploy 'natures-pl-members' to storeinfocus.com/natures-pl-members
        if: steps.filter.outputs.natures-pl-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "natures-pl-members/*"
          target: "/var/www/storeinfocus.com/natures-pl-members"
          strip_components: 1

      - name: Deploy 'natures-es-members' to storeinfocus.com/natures-es-members
        if: steps.filter.outputs.natures-es-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "natures-es-members/*"
          target: "/var/www/storeinfocus.com/natures-es-members"
          strip_components: 1

      - name: Deploy 'Fishing' to storeinfocus.com/fish
        if: steps.filter.outputs.fishing == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "Fishing/*"
          target: "/var/www/storeinfocus.com/fish"
          strip_components: 1

      - name: Deploy 'Fishing-de' to storeinfocus.com/fish-de
        if: steps.filter.outputs.fishing-de == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "Fishing-de/*"
          target: "/var/www/storeinfocus.com/fish-de"
          strip_components: 1

      - name: Deploy 'Fishing-fr' to storeinfocus.com/fish-fr
        if: steps.filter.outputs.fishing-fr == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "Fishing-fr/*"
          target: "/var/www/storeinfocus.com/fish-fr"
          strip_components: 1

      - name: Deploy 'WW' to skillvault.blog/ww
        if: steps.filter.outputs.ww == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "WW/*"
          target: "/var/www/skillvault.blog/ww"
          strip_components: 1

      - name: Deploy 'chickens' to skillvault.blog/chickens
        if: steps.filter.outputs.chickens == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "chickens/*"
          target: "/var/www/skillvault.blog/chickens"
          strip_components: 1

      - name: Deploy 'chickens-de' to skillvault.blog/chickens-al
        if: steps.filter.outputs.chickens-de == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "chickens-de/*"
          target: "/var/www/skillvault.blog/chickens-al"
          strip_components: 1

      - name: Deploy 'ww-de' to skillvault.blog/ww-de
        if: steps.filter.outputs.ww-de == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "ww-de/*"
          target: "/var/www/skillvault.blog/ww-de"
          strip_components: 1

      - name: Deploy 'ww-fr' to skillvault.blog/ww-fr
        if: steps.filter.outputs.ww-fr == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "ww-fr/*"
          target: "/var/www/skillvault.blog/ww-fr"
          strip_components: 1

      - name: Deploy 'ww-it' to skillvault.blog/ww-it
        if: steps.filter.outputs.ww-it == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "ww-it/*"
          target: "/var/www/skillvault.blog/ww-it"
          strip_components: 1

      - name: Deploy 'ww-plans-fr' to skillvault.blog/ww-plans-fr
        if: steps.filter.outputs.ww-plans-fr == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "ww-plans-fr/*"
          target: "/var/www/skillvault.blog/ww-plans-fr"
          strip_components: 1

      - name: Deploy 'ww-plans-it' to skillvault.blog/ww-plans-it
        if: steps.filter.outputs.ww-plans-it == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "ww-plans-it/*"
          target: "/var/www/skillvault.blog/ww-plans-it"
          strip_components: 1

      - name: Deploy 'mw-de' to skillvault.blog/mw-de
        if: steps.filter.outputs.mw-de == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "mw-de/*"
          target: "/var/www/skillvault.blog/mw-de"
          strip_components: 1

      - name: Deploy 'mw' to skillvault.blog/mw
        if: steps.filter.outputs.mw == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "mw/*"
          target: "/var/www/skillvault.blog/mw"
          strip_components: 1

      - name: Deploy 'mw-pt' to skillvault.blog/mw-pt
        if: steps.filter.outputs.mw-pt == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "mw-pt/*"
          target: "/var/www/skillvault.blog/mw-pt"
          strip_components: 1

      - name: Deploy 'bkp' to skillvault.blog/bkp
        if: steps.filter.outputs.bkp == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "bkp/*"
          target: "/var/www/skillvault.blog/bkp"
          strip_components: 1

      - name: Deploy 'bkp-de' to skillvault.blog/bkp-de
        if: steps.filter.outputs.bkp-de == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "bkp-de/*"
          target: "/var/www/skillvault.blog/bkp-de"
          strip_components: 1

      - name: Deploy 'bkp-es' to skillvault.blog/bkp-es
        if: steps.filter.outputs.bkp-es == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "bkp-es/*"
          target: "/var/www/skillvault.blog/bkp-es"
          strip_components: 1

      - name: Deploy 'bkp-pt' to skillvault.blog/bkp-pt
        if: steps.filter.outputs.bkp-pt == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "bkp-pt/*"
          target: "/var/www/skillvault.blog/bkp-pt"
          strip_components: 1

      - name: Deploy 'hx-fr' to skillvault.blog/hx-fr
        if: steps.filter.outputs.hx-fr == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "hx-fr/*"
          target: "/var/www/skillvault.blog/hx-fr"
          strip_components: 1

      - name: Deploy 'hx-it' to skillvault.blog/hx-it
        if: steps.filter.outputs.hx-it == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "hx-it/*"
          target: "/var/www/skillvault.blog/hx-it"
          strip_components: 1

      # â”€â”€ BEEKEEPING MEMBERS AREAS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

      - name: Deploy 'beekeeping-members' to skillvault.blog/bkp-m
        if: steps.filter.outputs.beekeeping-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "beekeeping-members/*"
          target: "/var/www/skillvault.blog/bkp-m"
          strip_components: 1

      - name: Deploy 'beekeeping-de-members' to skillvault.blog/bkp-de-m
        if: steps.filter.outputs.beekeeping-de-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "beekeeping-de-members/*"
          target: "/var/www/skillvault.blog/bkp-de-m"
          strip_components: 1

      - name: Deploy 'beekeeping-fr-members' to skillvault.blog/hx-fr-m
        if: steps.filter.outputs.beekeeping-fr-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "beekeeping-fr-members/*"
          target: "/var/www/skillvault.blog/hx-fr-m"
          strip_components: 1

      - name: Deploy 'beekeeping-it-members' to skillvault.blog/hx-it-m
        if: steps.filter.outputs.beekeeping-it-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "beekeeping-it-members/*"
          target: "/var/www/skillvault.blog/hx-it-m"
          strip_components: 1

      - name: Deploy 'beekeeping-es-members' to skillvault.blog/hx-es-m
        if: steps.filter.outputs.beekeeping-es-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "beekeeping-es-members/*"
          target: "/var/www/skillvault.blog/hx-es-m"
          strip_components: 1

      - name: Deploy 'beekeeping-pt-members' to skillvault.blog/hx-pt-m
        if: steps.filter.outputs.beekeeping-pt-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "beekeeping-pt-members/*"
          target: "/var/www/skillvault.blog/hx-pt-m"
          strip_components: 1

      - name: Deploy 'beekeeping-nl-members' to skillvault.blog/bkp-nl-m
        if: steps.filter.outputs.beekeeping-nl-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "beekeeping-nl-members/*"
          target: "/var/www/skillvault.blog/bkp-nl-m"
          strip_components: 1

      - name: Deploy 'beekeeping-pl-members' to skillvault.blog/bkp-pl-m
        if: steps.filter.outputs.beekeeping-pl-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "beekeeping-pl-members/*"
          target: "/var/www/skillvault.blog/bkp-pl-m"
          strip_components: 1

      - name: Deploy 'beekeeping-cs-members' to skillvault.blog/bkp-cs-m
        if: steps.filter.outputs.beekeeping-cs-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "beekeeping-cs-members/*"
          target: "/var/www/skillvault.blog/bkp-cs-m"
          strip_components: 1

      - name: Deploy 'beekeeping-el-members' to skillvault.blog/bkp-el-m
        if: steps.filter.outputs.beekeeping-el-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "beekeeping-el-members/*"
          target: "/var/www/skillvault.blog/bkp-el-m"
          strip_components: 1

      - name: Deploy 'beekeeping-ro-members' to skillvault.blog/bkp-ro-m
        if: steps.filter.outputs.beekeeping-ro-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "beekeeping-ro-members/*"
          target: "/var/www/skillvault.blog/bkp-ro-m"
          strip_components: 1

      - name: Deploy 'beekeeping-hu-members' to skillvault.blog/bkp-hu-m
        if: steps.filter.outputs.beekeeping-hu-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "beekeeping-hu-members/*"
          target: "/var/www/skillvault.blog/bkp-hu-m"
          strip_components: 1

      # â”€â”€ WOODWORKING MEMBERS AREAS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

      - name: Deploy 'ww-members' to skillvault.blog/ww-m
        if: steps.filter.outputs.ww-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "ww-members/*"
          target: "/var/www/skillvault.blog/ww-m"
          strip_components: 1

      - name: Deploy 'ww-de-members' to skillvault.blog/ww-de-m
        if: steps.filter.outputs.ww-de-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "ww-de-members/*"
          target: "/var/www/skillvault.blog/ww-de-m"
          strip_components: 1

      # â”€â”€ METALWORKING MEMBERS AREAS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

      - name: Deploy 'metalon-members' to skillvault.blog/mw-m
        if: steps.filter.outputs.metalon-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "metalon-members/*"
          target: "/var/www/skillvault.blog/mw-m"
          strip_components: 1

      # â”€â”€ EXCEL â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

      - name: Deploy 'excel' to skillvault.blog/excel
        if: steps.filter.outputs.excel == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "excel/*"
          target: "/var/www/skillvault.blog/excel"
          strip_components: 1

      - name: Deploy 'excel-plans-fr' to skillvault.blog/excel-plans-fr
        if: steps.filter.outputs.excel-plans-fr == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "excel-plans-fr/*"
          target: "/var/www/skillvault.blog/excel-plans-fr"
          strip_components: 1

      - name: Deploy 'excel-plans-de' to skillvault.blog/excel-plans-de
        if: steps.filter.outputs.excel-plans-de == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "excel-plans-de/*"
          target: "/var/www/skillvault.blog/excel-plans-de"
          strip_components: 1

      - name: Deploy 'excel-plans-es' to skillvault.blog/excel-plans-es
        if: steps.filter.outputs.excel-plans-es == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "excel-plans-es/*"
          target: "/var/www/skillvault.blog/excel-plans-es"
          strip_components: 1

      - name: Deploy 'excel-plans-it' to skillvault.blog/excel-plans-it
        if: steps.filter.outputs.excel-plans-it == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "excel-plans-it/*"
          target: "/var/www/skillvault.blog/excel-plans-it"
          strip_components: 1

      - name: Deploy 'excel-plans-pt' to skillvault.blog/excel-plans-pt
        if: steps.filter.outputs.excel-plans-pt == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "excel-plans-pt/*"
          target: "/var/www/skillvault.blog/excel-plans-pt"
          strip_components: 1

      - name: Deploy 'excel-members' to skillvault.blog/excel-m
        if: steps.filter.outputs.excel-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "excel-members/*"
          target: "/var/www/skillvault.blog/excel-m"
          strip_components: 1

      - name: Deploy 'excel-de-members' to skillvault.blog/excel-de-m
        if: steps.filter.outputs.excel-de-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "excel-de-members/*"
          target: "/var/www/skillvault.blog/excel-de-m"
          strip_components: 1

      - name: Deploy 'excel-pl-members' to skillvault.blog/excel-pl-m
        if: steps.filter.outputs.excel-pl-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "excel-pl-members/*"
          target: "/var/www/skillvault.blog/excel-pl-m"
          strip_components: 1

      - name: Deploy 'excel-fr-members' to skillvault.blog/excel-fr-m
        if: steps.filter.outputs.excel-fr-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "excel-fr-members/*"
          target: "/var/www/skillvault.blog/excel-fr-m"
          strip_components: 1

      - name: Deploy 'excel-es-members' to skillvault.blog/excel-es-m
        if: steps.filter.outputs.excel-es-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "excel-es-members/*"
          target: "/var/www/skillvault.blog/excel-es-m"
          strip_components: 1

      - name: Deploy 'excel-it-members' to skillvault.blog/excel-it-m
        if: steps.filter.outputs.excel-it-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "excel-it-members/*"
          target: "/var/www/skillvault.blog/excel-it-m"
          strip_components: 1

      - name: Deploy 'excel-pt-members' to skillvault.blog/excel-pt-m
        if: steps.filter.outputs.excel-pt-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "excel-pt-members/*"
          target: "/var/www/skillvault.blog/excel-pt-m"
          strip_components: 1

      - name: Deploy 'nature-members-es' to skillvault.blog/nature-members-es
        if: steps.filter.outputs.nature-members-es == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-members-es/*"
          target: "/var/www/skillvault.blog/nature-members-es"
          strip_components: 1

      - name: Deploy 'nature-bg-members' to skillvault.blog/nature-members-bg
        if: steps.filter.outputs.nature-bg-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-bg-members/*"
          target: "/var/www/skillvault.blog/nature-members-bg"
          strip_components: 1

      - name: Deploy 'nature-cs-members' to skillvault.blog/nature-members-cs
        if: steps.filter.outputs.nature-cs-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-cs-members/*"
          target: "/var/www/skillvault.blog/nature-members-cs"
          strip_components: 1

      - name: Deploy 'nature-da-members' to skillvault.blog/nature-members-da
        if: steps.filter.outputs.nature-da-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-da-members/*"
          target: "/var/www/skillvault.blog/nature-members-da"
          strip_components: 1

      - name: Deploy 'nature-de-members' to skillvault.blog/nature-members-de
        if: steps.filter.outputs.nature-de-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-de-members/*"
          target: "/var/www/skillvault.blog/nature-members-de"
          strip_components: 1

      - name: Deploy 'nature-fi-members' to skillvault.blog/nature-members-fi
        if: steps.filter.outputs.nature-fi-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-fi-members/*"
          target: "/var/www/skillvault.blog/nature-members-fi"
          strip_components: 1

      - name: Deploy 'nature-fr-members' to skillvault.blog/nature-members-fr
        if: steps.filter.outputs.nature-fr-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-fr-members/*"
          target: "/var/www/skillvault.blog/nature-members-fr"
          strip_components: 1

      - name: Deploy 'nature-hr-members' to skillvault.blog/nature-members-hr
        if: steps.filter.outputs.nature-hr-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-hr-members/*"
          target: "/var/www/skillvault.blog/nature-members-hr"
          strip_components: 1

      - name: Deploy 'nature-hu-members' to skillvault.blog/nature-members-hu
        if: steps.filter.outputs.nature-hu-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-hu-members/*"
          target: "/var/www/skillvault.blog/nature-members-hu"
          strip_components: 1

      - name: Deploy 'nature-members-it' to skillvault.blog/nature-members-it
        if: steps.filter.outputs.nature-members-it == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-members-it/*"
          target: "/var/www/skillvault.blog/nature-members-it"
          strip_components: 1

      - name: Deploy 'nature-nl-members' to skillvault.blog/nature-members-nl
        if: steps.filter.outputs.nature-nl-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-nl-members/*"
          target: "/var/www/skillvault.blog/nature-members-nl"
          strip_components: 1

      - name: Deploy 'nature-no-members' to skillvault.blog/nature-members-no
        if: steps.filter.outputs.nature-no-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-no-members/*"
          target: "/var/www/skillvault.blog/nature-members-no"
          strip_components: 1

      - name: Deploy 'nature-pl-members' to skillvault.blog/nature-members-pl
        if: steps.filter.outputs.nature-pl-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-pl-members/*"
          target: "/var/www/skillvault.blog/nature-members-pl"
          strip_components: 1

      - name: Deploy 'nature-pt-members' to skillvault.blog/nature-members-pt
        if: steps.filter.outputs.nature-pt-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-pt-members/*"
          target: "/var/www/skillvault.blog/nature-members-pt"
          strip_components: 1

      - name: Deploy 'nature-sk-members' to skillvault.blog/nature-members-sk
        if: steps.filter.outputs.nature-sk-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-sk-members/*"
          target: "/var/www/skillvault.blog/nature-members-sk"
          strip_components: 1

      - name: Deploy 'natures-sk-members' to skillvault.blog/nature-members-sk
        if: steps.filter.outputs.natures-sk-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "natures-sk-members/*"
          target: "/var/www/skillvault.blog/nature-members-sk"
          strip_components: 1

      - name: Deploy 'nature-sl-members' to skillvault.blog/nature-members-sl
        if: steps.filter.outputs.nature-sl-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-sl-members/*"
          target: "/var/www/skillvault.blog/nature-members-sl"
          strip_components: 1

      - name: Deploy 'nature-sv-members' to skillvault.blog/nature-members-sv
        if: steps.filter.outputs.nature-sv-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-sv-members/*"
          target: "/var/www/skillvault.blog/nature-members-sv"
          strip_components: 1

      - name: Deploy 'nature-members' to skillvault.blog/nature-members
        if: steps.filter.outputs.nature-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-members/*"
          target: "/var/www/skillvault.blog/nature-members"
          strip_components: 1

      - name: Deploy 'nature-el-members' to skillvault.blog/nature-members-el
        if: steps.filter.outputs.nature-el-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-el-members/*"
          target: "/var/www/skillvault.blog/nature-members-el"
          strip_components: 1

      - name: Deploy 'nature-uk-members' to skillvault.blog/nature-members-uk
        if: steps.filter.outputs.nature-uk-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-uk-members/*"
          target: "/var/www/skillvault.blog/nature-members-uk"
          strip_components: 1

      - name: Deploy 'nature-ro-members' to skillvault.blog/nature-members-ro
        if: steps.filter.outputs.nature-ro-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-ro-members/*"
          target: "/var/www/skillvault.blog/nature-members-ro"
          strip_components: 1

      - name: Deploy 'nature-bs-members' to skillvault.blog/nature-members-bs
        if: steps.filter.outputs.nature-bs-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-bs-members/*"
          target: "/var/www/skillvault.blog/nature-members-bs"
          strip_components: 1

      - name: Deploy 'nature-ca-members' to skillvault.blog/nature-members-ca
        if: steps.filter.outputs.nature-ca-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-ca-members/*"
          target: "/var/www/skillvault.blog/nature-members-ca"
          strip_components: 1

      - name: Deploy 'nature-zh-members' to skillvault.blog/nature-members-zh
        if: steps.filter.outputs.nature-zh-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-zh-members/*"
          target: "/var/www/skillvault.blog/nature-members-zh"
          strip_components: 1

      - name: Deploy 'nature-ko-members' to skillvault.blog/nature-members-ko
        if: steps.filter.outputs.nature-ko-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-ko-members/*"
          target: "/var/www/skillvault.blog/nature-members-ko"
          strip_components: 1

      - name: Deploy 'nature-ja-members' to skillvault.blog/nature-members-ja
        if: steps.filter.outputs.nature-ja-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-ja-members/*"
          target: "/var/www/skillvault.blog/nature-members-ja"
          strip_components: 1

      - name: Deploy 'nature-lv-members' to skillvault.blog/nature-members-lv
        if: steps.filter.outputs.nature-lv-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-lv-members/*"
          target: "/var/www/skillvault.blog/nature-members-lv"
          strip_components: 1

      - name: Deploy 'nature-mk-members' to skillvault.blog/nature-members-mk
        if: steps.filter.outputs.nature-mk-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-mk-members/*"
          target: "/var/www/skillvault.blog/nature-members-mk"
          strip_components: 1

      - name: Deploy 'nature-sr-members' to skillvault.blog/nature-members-sr
        if: steps.filter.outputs.nature-sr-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-sr-members/*"
          target: "/var/www/skillvault.blog/nature-members-sr"
          strip_components: 1

      - name: Deploy 'nature-he-members' to skillvault.blog/natural-members-he
        if: steps.filter.outputs.nature-he-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-he-members/*"
          target: "/var/www/skillvault.blog/natural-members-he"
          strip_components: 1

      - name: Deploy 'nature-ar-members' to skillvault.blog/nature-members-ar
        if: steps.filter.outputs.nature-ar-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-ar-members/*"
          target: "/var/www/skillvault.blog/nature-members-ar"
          strip_components: 1

      - name: Deploy 'nature-ru-members' to skillvault.blog/nature-members-ru
        if: steps.filter.outputs.nature-ru-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-ru-members/*"
          target: "/var/www/skillvault.blog/nature-members-ru"
          strip_components: 1

      - name: Deploy 'nature-tr-members' to skillvault.blog/nature-members-tr
        if: steps.filter.outputs.nature-tr-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-tr-members/*"
          target: "/var/www/skillvault.blog/nature-members-tr"
          strip_components: 1

      - name: Deploy 'nature-lt-members' to skillvault.blog/nature-members-lt
        if: steps.filter.outputs.nature-lt-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "nature-lt-members/*"
          target: "/var/www/skillvault.blog/nature-members-lt"
          strip_components: 1

      - name: Deploy 'gfree-members' to naturalmethods.blog/g-free-sv
        if: steps.filter.outputs.gfree-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-members/*"
          target: "/var/www/naturalmethods.blog/g-free-sv"
          strip_components: 1

      - name: Deploy 'gfree-pl-members' to naturalmethods.blog/g-free-pl
        if: steps.filter.outputs.gfree-pl-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-pl-members/*"
          target: "/var/www/naturalmethods.blog/g-free-pl"
          strip_components: 1

      - name: Deploy 'gfree-nl-members' to naturalmethods.blog/g-free-nl
        if: steps.filter.outputs.gfree-nl-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-nl-members/*"
          target: "/var/www/naturalmethods.blog/g-free-nl"
          strip_components: 1

      - name: Deploy 'gfree-de-members' to naturalmethods.blog/g-free-de
        if: steps.filter.outputs.gfree-de-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-de-members/*"
          target: "/var/www/naturalmethods.blog/g-free-de"
          strip_components: 1

      - name: Deploy 'gfree-da-members' to naturalmethods.blog/g-free-da
        if: steps.filter.outputs.gfree-da-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-da-members/*"
          target: "/var/www/naturalmethods.blog/g-free-da"
          strip_components: 1

      - name: Deploy 'gfree-en-members' to naturalmethods.blog/g-free
        if: steps.filter.outputs.gfree-en-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-en-members/*"
          target: "/var/www/naturalmethods.blog/g-free"
          strip_components: 1

      - name: Deploy 'gfree-el-members' to naturalmethods.blog/g-free-el
        if: steps.filter.outputs.gfree-el-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-el-members/*"
          target: "/var/www/naturalmethods.blog/g-free-el"
          strip_components: 1

      - name: Deploy 'gfree-fr-members' to naturalmethods.blog/g-free-fr
        if: steps.filter.outputs.gfree-fr-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-fr-members/*"
          target: "/var/www/naturalmethods.blog/g-free-fr"
          strip_components: 1

      - name: Deploy 'gfree-it-members' to naturalmethods.blog/g-free-it
        if: steps.filter.outputs.gfree-it-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-it-members/*"
          target: "/var/www/naturalmethods.blog/g-free-it"
          strip_components: 1

      - name: Deploy 'gfree-es-members' to naturalmethods.blog/g-free-es
        if: steps.filter.outputs.gfree-es-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-es-members/*"
          target: "/var/www/naturalmethods.blog/g-free-es"
          strip_components: 1

      - name: Deploy 'gfree-hr-members' to naturalmethods.blog/g-free-hr
        if: steps.filter.outputs.gfree-hr-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-hr-members/*"
          target: "/var/www/naturalmethods.blog/g-free-hr"
          strip_components: 1

      - name: Deploy 'gfree-fi-members' to naturalmethods.blog/g-free-fi
        if: steps.filter.outputs.gfree-fi-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-fi-members/*"
          target: "/var/www/naturalmethods.blog/g-free-fi"
          strip_components: 1

      - name: Deploy 'gfree-ar-members' to naturalmethods.blog/g-free-ar
        if: steps.filter.outputs.gfree-ar-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-ar-members/*"
          target: "/var/www/naturalmethods.blog/g-free-ar"
          strip_components: 1

      - name: Deploy 'gfree-bg-members' to naturalmethods.blog/g-free-bg
        if: steps.filter.outputs.gfree-bg-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-bg-members/*"
          target: "/var/www/naturalmethods.blog/g-free-bg"
          strip_components: 1

      - name: Deploy 'gfree-hu-members' to naturalmethods.blog/g-free-hu
        if: steps.filter.outputs.gfree-hu-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-hu-members/*"
          target: "/var/www/naturalmethods.blog/g-free-hu"
          strip_components: 1

      - name: Deploy 'gfree-no-members' to naturalmethods.blog/g-free-no
        if: steps.filter.outputs.gfree-no-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-no-members/*"
          target: "/var/www/naturalmethods.blog/g-free-no"
          strip_components: 1

      - name: Deploy 'gfree-ga-members' to naturalmethods.blog/g-free-ga
        if: steps.filter.outputs.gfree-ga-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-ga-members/*"
          target: "/var/www/naturalmethods.blog/g-free-ga"
          strip_components: 1

      - name: Deploy 'gfree-ro-members' to naturalmethods.blog/g-free-ro
        if: steps.filter.outputs.gfree-ro-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-ro-members/*"
          target: "/var/www/naturalmethods.blog/g-free-ro"
          strip_components: 1

      - name: Deploy 'gfree-sr-members' to naturalmethods.blog/g-free-sr
        if: steps.filter.outputs.gfree-sr-members == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SECRET }}
          source: "gfree-sr-members/*"
          target: "/var/www/naturalmethods.blog/g-free-sr"
          strip_components: 1

